### ISSUE TITLE
crash bug found when setup the testbed with the script 

### ISSUE THREAD

**Issue by dreamfly281** [nknorg/nkn#105]
X@bogon:~/projects/src/github.com/nknorg/nkn$ make all
go build  -ldflags "-X github.com/nknorg/nkn/util/config.Version=5b4e8-dirty"  nknd.go
go build  -ldflags "-X github.com/nknorg/nkn/cli/common.Version=5b4e8-dirty" nknc.go
yanbo@bogon:~/projects/src/github.com/nknorg/nkn$ ./test/create_testbed.sh   10 test
Password:Re-enter Password:Address				 Public Key
-------				 ----------
ATajt3w8ZZLHcmaZSNYtutaUafA5H1MAKD 0243cdabbe0f4a5c8d32d8454b94f6fa28a063e5f8735848ef2a49fed297c1f80b
Password:Re-enter Password:Address				 Public Key
-------				 ----------
AbgztA5p2pHuKRZBYz2LZ8b3jC7fwojF9N 021b83f66011450c186e2938def975e34dba43f92ccdf6f37d7f12465a28a7e853
Password:Re-enter Password:Address				 Public Key
-------				 ----------
AUyTtKhzzAX2irqPQekYc17xpxVb7Ek3es 0288ea16ee0338e3e71a91c62bd07cd026c64bed548aab121eb7c34c032d8edbda
Password:Re-enter Password:Address				 Public Key
-------				 ----------
ALf75ALXrrfLkQhsRFKYQB433tw2ivQzd6 0399977060ce5a8d600eee9ccfd26cece0689cba0c18d11b183c19bfa873ecd2f8
Password:Re-enter Password:Address				 Public Key
-------				 ----------
AR4uBASuvu24WYtBATB2KR4kfRLvcHu8KL 02a0d73f5c2c712ebcaae6fe3b88f6d6e9a566893b183a7535eea2989a078b6aab
Password:Re-enter Password:Address				 Public Key
-------				 ----------
ASLhN1BctFz2E32zPQngJKhLS5QJ5DzCnG 03806a48de343cf59a212067b23c4c1ed209e6c0f695c0e0864409d61ba7fd5cf1
Password:Re-enter Password:Address				 Public Key
-------				 ----------
AQ7TYkeyNdzU6LqtkejWPgLyG8YPdY5tHR 028eed00d9e286d9aed67379c48c2cae89373e2b7fe0b72e3a81fb2ddffa1751bc
Password:Re-enter Password:panic: crypto/cipher: input not full blocks

goroutine 1 [running]:
crypto/cipher.(*cbcEncrypter).CryptBlocks(0xc420017220, 0xc4200cbb80, 0x1f, 0x1f, 0xc4200cba61, 0x1f, 0x1f)
	/usr/local/Cellar/go/1.8/libexec/src/crypto/cipher/cbc.go:57 +0x2f7
github.com/nknorg/nkn/crypto.AesEncrypt(0xc4200cba61, 0x1f, 0x1f, 0xc4200cb5a0, 0x20, 0x20, 0xc420013da0, 0x10, 0x10, 0x15486e0, ...)
	/Users/yanbo/projects/src/github.com/nknorg/nkn/crypto/helper.go:33 +0x1cb
github.com/nknorg/nkn/wallet.(*WalletImpl).CreateAccount(0xc420068540, 0x0, 0x0, 0x0, 0xc420013da0, 0x10)
	/Users/yanbo/projects/src/github.com/nknorg/nkn/wallet/wallet.go:182 +0xdf
github.com/nknorg/nkn/wallet.NewWallet(0x139a465, 0xa, 0xc420013a70, 0x7, 0x8, 0x100cd01, 0x1399db7, 0x139937a, 0x1)
	/Users/yanbo/projects/src/github.com/nknorg/nkn/wallet/wallet.go:89 +0x481
github.com/nknorg/nkn/cli/wallet.walletAction(0xc4200d6280, 0x0, 0xc4200d6280)
	/Users/yanbo/projects/src/github.com/nknorg/nkn/cli/wallet/wallet.go:74 +0x26e
github.com/nknorg/nkn/vendor/github.com/urfave/cli.HandleAction(0x132a8a0, 0x13ac650, 0xc4200d6280, 0xc420068400, 0x0)
	/Users/yanbo/projects/src/github.com/nknorg/nkn/vendor/github.com/urfave/cli/app.go:485 +0xd4
github.com/nknorg/nkn/vendor/github.com/urfave/cli.Command.Run(0x1398f86, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x139e60d, 0x15, 0x0, ...)
	/Users/yanbo/projects/src/github.com/nknorg/nkn/vendor/github.com/urfave/cli/command.go:207 +0xb72
github.com/nknorg/nkn/vendor/github.com/urfave/cli.(*App).Run(0xc4200884e0, 0xc420010120, 0x3, 0x3, 0x0, 0x0)
	/Users/yanbo/projects/src/github.com/nknorg/nkn/vendor/github.com/urfave/cli/app.go:250 +0x7d0
main.main()
	/Users/yanbo/projects/src/github.com/nknorg/nkn/nknc.go:42 +0x53a

**Comment by gdmmx** [comment]
Reproduce this bug today during deploy large-scale TestNet.  (3 case in 499 vm)

From https://github.com/nknorg/nkn
   9dbd651..779b7a8  master     -> origin/master
Updating 9dbd651..779b7a8
Fast-forward
 crypto/encode.go            | 10 +++++-----
 test/ci/gcloud_instances.sh |  4 ++--
 2 files changed, 7 insertions(+), 7 deletions(-)
go build  -ldflags "-s -w -X github.com/nknorg/nkn/util/config.Version=v0.1-alpha-91-g779b"  nknd.go
go build  -ldflags "-s -w -X github.com/nknorg/nkn/cli/common.Version=v0.1-alpha-91-g779b" nknc.go
Password:Re-enter Password:panic: crypto/cipher: input not full blocks

goroutine 1 [running]:
panic(0x719120, 0x7d7f40)
	/usr/lib/go-1.10/src/runtime/panic.go:551 +0x3c1 fp=0xc4200574f8 sp=0xc420057458 pc=0x42ac41
crypto/cipher.(*cbcEncrypter).CryptBlocks(0xc4202480f0, 0xc420258720, 0x1f, 0x1f, 0xc4202585a1, 0x1f, 0x1f)
	/usr/lib/go-1.10/src/crypto/cipher/cbc.go:57 +0x28a fp=0xc420057568 sp=0xc4200574f8 pc=0x50d2ba
github.com/nknorg/nkn/crypto.AesEncrypt(0xc4202585a1, 0x1f, 0x1f, 0xc42029e720, 0x20, 0x20, 0xc4203aaed0, 0x10, 0x10, 0x18, ...)
	/home/admin/nknorg/src/github.com/nknorg/nkn/crypto/helper.go:34 +0x1a1 fp=0xc4200575d8 sp=0xc420057568 pc=0x548a71
github.com/nknorg/nkn/vault.(*WalletImpl).CreateAccount(0xc42005c120, 0x0, 0x0, 0x0, 0xc4203aaed0, 0x10)
	/home/admin/nknorg/src/github.com/nknorg/nkn/vault/wallet.go:186 +0xdf fp=0xc420057698 sp=0xc4200575d8 pc=0x6d4d0f
github.com/nknorg/nkn/vault.NewWallet(0x799403, 0xa, 0xc4203aac40, 0x7, 0x8, 0x6afb01, 0x736dc0, 0xc4200578d0, 0x798567)
	/home/admin/nknorg/src/github.com/nknorg/nkn/vault/wallet.go:93 +0x45c fp=0xc4200577d0 sp=0xc420057698 pc=0x6d42ec
github.com/nknorg/nkn/cli/wallet.walletAction(0xc42017f040, 0x0, 0xfe)
	/home/admin/nknorg/src/github.com/nknorg/nkn/cli/wallet/wallet.go:74 +0x22a fp=0xc420057980 sp=0xc4200577d0 pc=0x6ddbfa
github.com/nknorg/nkn/vendor/github.com/urfave/cli.HandleAction(0x724c60, 0x7af568, 0xc42017f040, 0xc42005df00, 0x0)
	/home/admin/nknorg/src/github.com/nknorg/nkn/vendor/github.com/urfave/cli/app.go:485 +0xc8 fp=0xc4200579a8 sp=0xc420057980 pc=0x6abe98
github.com/nknorg/nkn/vendor/github.com/urfave/cli.Command.Run(0x79823e, 0x6, 0x0, 0x0, 0x0, 0x0, 0x0, 0x79d110, 0x15, 0x0, ...)
	/home/admin/nknorg/src/github.com/nknorg/nkn/vendor/github.com/urfave/cli/command.go:207 +0xa35 fp=0xc420057c58 sp=0xc4200579a8 pc=0x6ad335
github.com/nknorg/nkn/vendor/github.com/urfave/cli.(*App).Run(0xc420088340, 0xc420010090, 0x3, 0x3, 0x0, 0x0)
	/home/admin/nknorg/src/github.com/nknorg/nkn/vendor/github.com/urfave/cli/app.go:250 +0x700 fp=0xc420057e68 sp=0xc420057c58 pc=0x6aa130
main.main()
	/home/admin/nknorg/src/github.com/nknorg/nkn/nknc.go:44 +0x57e fp=0xc420057f88 sp=0xc420057e68 pc=0x6df29e
runtime.main()
	/usr/lib/go-1.10/src/runtime/proc.go:198 +0x212 fp=0xc420057fe0 sp=0xc420057f88 pc=0x42c952
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420057fe8 sp=0xc420057fe0 pc=0x456d91

goroutine 2 [force gc (idle)]:
runtime.gopark(0x7afcd0, 0x9883c0, 0x79a967, 0xf, 0x7afb14, 0x1)
	/usr/lib/go-1.10/src/runtime/proc.go:291 +0x11a fp=0xc420032768 sp=0xc420032748 pc=0x42cdaa
runtime.goparkunlock(0x9883c0, 0x79a967, 0xf, 0x14, 0x1)
	/usr/lib/go-1.10/src/runtime/proc.go:297 +0x5e fp=0xc4200327a8 sp=0xc420032768 pc=0x42ce5e
runtime.forcegchelper()
	/usr/lib/go-1.10/src/runtime/proc.go:248 +0xcc fp=0xc4200327e0 sp=0xc4200327a8 pc=0x42cbec
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4200327e8 sp=0xc4200327e0 pc=0x456d91
created by runtime.init.4
	/usr/lib/go-1.10/src/runtime/proc.go:237 +0x35

goroutine 3 [GC sweep wait]:
runtime.gopark(0x7afcd0, 0x9884e0, 0x799e9a, 0xd, 0x452214, 0x1)
	/usr/lib/go-1.10/src/runtime/proc.go:291 +0x11a fp=0xc420032f60 sp=0xc420032f40 pc=0x42cdaa
runtime.goparkunlock(0x9884e0, 0x799e9a, 0xd, 0x14, 0x1)
	/usr/lib/go-1.10/src/runtime/proc.go:297 +0x5e fp=0xc420032fa0 sp=0xc420032f60 pc=0x42ce5e
runtime.bgsweep(0xc42001e070)
	/usr/lib/go-1.10/src/runtime/mgcsweep.go:71 +0x12c fp=0xc420032fd8 sp=0xc420032fa0 pc=0x41fe4c
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420032fe0 sp=0xc420032fd8 pc=0x456d91
created by runtime.gcenable
	/usr/lib/go-1.10/src/runtime/mgc.go:216 +0x58

goroutine 4 [finalizer wait]:
runtime.gopark(0x7afcd0, 0x9a6240, 0x79a50b, 0xe, 0x14, 0x1)
	/usr/lib/go-1.10/src/runtime/proc.go:291 +0x11a fp=0xc420033718 sp=0xc4200336f8 pc=0x42cdaa
runtime.goparkunlock(0x9a6240, 0x79a50b, 0xe, 0x14, 0x1)
	/usr/lib/go-1.10/src/runtime/proc.go:297 +0x5e fp=0xc420033758 sp=0xc420033718 pc=0x42ce5e
runtime.runfinq()
	/usr/lib/go-1.10/src/runtime/mfinal.go:175 +0xad fp=0xc4200337e0 sp=0xc420033758 pc=0x416e6d
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4200337e8 sp=0xc4200337e0 pc=0x456d91
created by runtime.createfing
	/usr/lib/go-1.10/src/runtime/mfinal.go:156 +0x62

goroutine 6 [syscall]:
runtime.notetsleepg(0x98cac0, 0x14f450d191, 0x1)
	/usr/lib/go-1.10/src/runtime/lock_futex.go:227 +0x42 fp=0xc420033f60 sp=0xc420033f30 pc=0x410ad2
runtime.timerproc(0x98caa0)
	/usr/lib/go-1.10/src/runtime/time.go:261 +0x2e7 fp=0xc420033fd8 sp=0xc420033f60 pc=0x448587
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420033fe0 sp=0xc420033fd8 pc=0x456d91
created by runtime.(*timersBucket).addtimerLocked
	/usr/lib/go-1.10/src/runtime/time.go:160 +0x107

goroutine 13 [IO wait]:
runtime.gopark(0x7afca0, 0x7f9e670b1f28, 0x7983c4, 0x7, 0x46c71b, 0x5)
	/usr/lib/go-1.10/src/runtime/proc.go:291 +0x11a fp=0xc420043698 sp=0xc420043678 pc=0x42cdaa
runtime.netpollblock(0x7f9e670b1f00, 0xffffff0000000072, 0x0)
	/usr/lib/go-1.10/src/runtime/netpoll.go:366 +0xaa fp=0xc4200436e0 sp=0xc420043698 pc=0x4280ca
internal/poll.runtime_pollWait(0x7f9e670b1f00, 0x72, 0xc420043760)
	/usr/lib/go-1.10/src/runtime/netpoll.go:173 +0x57 fp=0xc420043708 sp=0xc4200436e0 pc=0x427747
internal/poll.(*pollDesc).wait(0xc4200fab18, 0x72, 0xffffffffffffff00, 0x7da7e0, 0x950450)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:85 +0x9b fp=0xc420043738 sp=0xc420043708 pc=0x4815db
internal/poll.(*pollDesc).waitRead(0xc4200fab18, 0xc4200aec00, 0x400, 0x400)
	/usr/lib/go-1.10/src/internal/poll/fd_poll_runtime.go:90 +0x3d fp=0xc420043770 sp=0xc420043738 pc=0x48165d
internal/poll.(*FD).Read(0xc4200fab00, 0xc4200aec00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/internal/poll/fd_unix.go:157 +0x17d fp=0xc4200437c0 sp=0xc420043770 pc=0x4824bd
net.(*netFD).Read(0xc4200fab00, 0xc4200aec00, 0x400, 0x400, 0xc4200438e0, 0xc4200438e8, 0x411809)
	/usr/lib/go-1.10/src/net/fd_unix.go:202 +0x4f fp=0xc420043820 sp=0xc4200437c0 pc=0x579c0f
net.(*conn).Read(0xc42000e0e0, 0xc4200aec00, 0x400, 0x400, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/net/net.go:176 +0x6a fp=0xc420043880 sp=0xc420043820 pc=0x58ad1a
crypto/tls.(*block).readFromUntil(0xc4201382d0, 0x7f9e670b2110, 0xc42000e0e0, 0x5, 0xc42000e0e0, 0x8)
	/usr/lib/go-1.10/src/crypto/tls/conn.go:493 +0x96 fp=0xc4200438c8 sp=0xc420043880 pc=0x5e6c46
crypto/tls.(*Conn).readRecord(0xc4200bee00, 0x7afd17, 0xc4200bef20, 0x452ff0)
	/usr/lib/go-1.10/src/crypto/tls/conn.go:595 +0xe0 fp=0xc420043a70 sp=0xc4200438c8 pc=0x5e7150
crypto/tls.(*Conn).Read(0xc4200bee00, 0xc420198000, 0x1000, 0x1000, 0x0, 0x0, 0x0)
	/usr/lib/go-1.10/src/crypto/tls/conn.go:1156 +0x100 fp=0xc420043ac8 sp=0xc420043a70 pc=0x5ea6f0
net/http.(*persistConn).Read(0xc420013200, 0xc420198000, 0x1000, 0x1000, 0xc420043b98, 0x404fd5, 0xc4203c5440)
	/usr/lib/go-1.10/src/net/http/transport.go:1453 +0x136 fp=0xc420043b40 sp=0xc420043ac8 pc=0x668e56
bufio.(*Reader).fill(0xc42005dce0)
	/usr/lib/go-1.10/src/bufio/bufio.go:100 +0x11e fp=0xc420043b90 sp=0xc420043b40 pc=0x53a92e
bufio.(*Reader).Peek(0xc42005dce0, 0x1, 0x0, 0x0, 0x0, 0xc4203c5380, 0x0)
	/usr/lib/go-1.10/src/bufio/bufio.go:132 +0x3a fp=0xc420043ba8 sp=0xc420043b90 pc=0x53aa7a
net/http.(*persistConn).readLoop(0xc420013200)
	/usr/lib/go-1.10/src/net/http/transport.go:1601 +0x185 fp=0xc420043fd8 sp=0xc420043ba8 pc=0x669915
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420043fe0 sp=0xc420043fd8 pc=0x456d91
created by net/http.(*Transport).dialConn
	/usr/lib/go-1.10/src/net/http/transport.go:1237 +0x95a

goroutine 14 [select]:
runtime.gopark(0x7afd10, 0x0, 0x7981d8, 0x6, 0x18, 0x1)
	/usr/lib/go-1.10/src/runtime/proc.go:291 +0x11a fp=0xc420045c90 sp=0xc420045c70 pc=0x42cdaa
runtime.selectgo(0xc420045f48, 0xc4200661e0)
	/usr/lib/go-1.10/src/runtime/select.go:392 +0xe50 fp=0xc420045e68 sp=0xc420045c90 pc=0x43bef0
net/http.(*persistConn).writeLoop(0xc420013200)
	/usr/lib/go-1.10/src/net/http/transport.go:1822 +0x14b fp=0xc420045fd8 sp=0xc420045e68 pc=0x66aedb
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc420045fe0 sp=0xc420045fd8 pc=0x456d91
created by net/http.(*Transport).dialConn
	/usr/lib/go-1.10/src/net/http/transport.go:1238 +0x97f

goroutine 12 [GC worker (idle)]:
runtime.gopark(0x7afb78, 0xc4204527b0, 0x79acc3, 0x10, 0xc420034714, 0x0)
	/usr/lib/go-1.10/src/runtime/proc.go:291 +0x11a fp=0xc420034748 sp=0xc420034728 pc=0x42cdaa
runtime.gcBgMarkWorker(0xc420020000)
	/usr/lib/go-1.10/src/runtime/mgc.go:1775 +0x130 fp=0xc4200347d8 sp=0xc420034748 pc=0x41aa60
runtime.goexit()
	/usr/lib/go-1.10/src/runtime/asm_amd64.s:2361 +0x1 fp=0xc4200347e0 sp=0xc4200347d8 pc=0x456d91
created by runtime.gcBgMarkStartWorkers
	/usr/lib/go-1.10/src/runtime/mgc.go:1723 +0x79
