### ISSUE TITLE
Add documentation for RPC/Rest/Websocket API

### ISSUE THREAD

**Issue by yilunzhang** [nknorg/nkn#131]

**Comment by d5c5ceb0** [comment]
the RPC/Websocket API reference is here:
https://github.com/nknorg/nkn/wiki/JSON-RPC-API-Reference
https://github.com/nknorg/nkn/wiki/Websocket-API-Reference

**Comment by NoelBright** [comment]
the RPC/Websocket API reference is here:
https://github.com/nknorg/nkn/wiki/JSON-RPC-API-Reference
https://github.com/nknorg/nkn/wiki/Websocket-API-Reference

**Comment by chauser123** [comment]
Thanks sorry

**Comment by abebeos** [comment]
@yilunzhang , looks like this one can be closed.
