### ISSUE TITLE
The first node started with "./nknd -test create" should not be configured as GenesisBlockProposer

### ISSUE THREAD

**Issue by doraemon0** [nknorg/nkn#157]
The first node is a bootstrap node. After networking started, the bootstrap node should be stopped. If use the first node as GenesisBlockProposer, when no signature chain sent in system, the default block proposer will missing. Then block producing will be blocked. So do not use the first node as GenesisBlockProposer in test version.

**Comment by yilunzhang** [comment]
This part of the readme is related:

> When the network contains enough nodes (more than the length of successor list plus one, by default 9+), stop the node that created the network in order for the relay service to work properly. Nodes joining the network later should use a live node as seed.
