### ISSUE TITLE
Should rejoin when node can't catch up with neighbors

### ISSUE THREAD

**Issue by doraemon0** [nknorg/nkn#196]
when node reconnect with neighbors, such as keepalive timeouts, the node should re-join network rather than exits.

**Comment by tjosm** [comment]
I'm also having this issue.
https://gyazo.com/0c6064580e3c8c34eb2de698a91cf6ff

My nodes keeps getting disconnected

**Comment by yilunzhang** [comment]
fixed in the upcoming version
