### ISSUE TITLE
Use protobuffer instead of JSON for websocket msg for binary data

### ISSUE THREAD

**Issue by yilunzhang** [nknorg/nkn#208]
### Description of the issue
Currently all websocket messages are encoded in JSON, which does not support transmitting binary data natively. Encode binary data with base64 introduces both CPU and bandwidth overhead. This can be avoided by sending binary data directly through websocket. The easy and backward/forward/cross-platform compatible way of doing it is to use protobuffer to encode/decode message.

### Issue-Type (put a `x` sign in the square brackets)
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

**Comment by yilunzhang** [comment]
Implemented in:
https://github.com/nknorg/nkn/pull/229
https://github.com/nknorg/nkn-client-js/pull/25

**Comment by grondilu** [comment]
I didn't know about protobuffers before I got interested in NKN.  From what I can tell, this serialization format seems tough to implement, and I don't understand what they mean by "language-neutral".  Compilers are available in only a handful of languages.  So far protobuffer has been the biggest hurdle I've met in implementing a client for my favorite language.

I understand the move from JSON to binary for the sake of efficiency, but a JSON backend should IMHO still be available for portability's sake.   JSON is easy to comprehend and to implement.

More generally, maybe there could be several serialization methods possible?  There are so many it seems unfortunate that only one is available for NKN :

https://en.wikipedia.org/wiki/Comparison_of_data-serialization_formats

I mean it should not be that much of an overhead right after the handshake to send a message about the format of the upcoming data or something.

**Comment by yilunzhang** [comment]
Protobuf is only used for internal client message encoding and is part of client-node communication protocol. It's transparent to SDK users. Supporting more encoding scheme won't affect how users use the SDK, so it's not our top priority to support more encoding scheme. Actually supporting more encoding scheme is a significant amount of work because the node and ALL SDK need to support them. We just need an encoding scheme that is as efficient as possible (for both bandwidth, CPU, RAM, etc), and protobuf serves that purpose well.

> From what I can tell, this serialization format seems tough to implement, and I don't understand what they mean by "language-neutral", as compilers are available in only a handful of languages, and writing one seems like a big task. So far protobuffer has been the biggest hurdle I've met in implementing a client for my favorite language.

What language are you trying to implement it? If you ever need to implement the serialization yourself, most likely you are doing it wrong unless it's a language that protobuf has absolutely no support (official or unofficial).

> Maybe it is still possible via JSON-rpc instead of websocket? I didn't see it mentioned anywhere in the documentation.

We definitely don't want to do client message via http (instead of websockets) because (1) http has terrible overhead, one message per rpc call has unacceptable performance for both client and node side, and (2) we need node to push messages to client in realtime, which makes websocket superior to http
