### ISSUE TITLE
NKN node on a Raspberry Pi

### ISSUE THREAD

**Issue by dreamfly281** [nknorg/nkn#214]
### Description of the issue
NKN team can you please make a YouTube video on how to set up a NKN node on a Raspberry Pi? It would be a good way to grow the NKN network since it has a lower barrier of entry cost wise.

### Issue-Type (put a `x` sign in the square brackets)
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement

### Checklist
- [ ] Running latest version of code.
- [x ] This issue has not been reported earlier.

Good suggestion, currently the software is written in Golang, it support to be compiled & running for arm processor which the Raspberry Pi used. but currently we are still focus on PC as the first priority due to lack of hands, if someone in community would like to do this, we'd glad to support no matter in technical or incentive.

**Comment by yilunzhang** [comment]
Resolved by #218
