### ISSUE TITLE
Huge log of "too many open files ..."

### ISSUE THREAD

**Issue by gdmmx** [nknorg/nkn#234]
### Description of the issue
Describe the issue you are experiencing.

### Issue-Type (put a `x` sign in the square brackets)
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* OS
Debian (stretch)
* Go version
go version go1.10.3 linux/amd64
* Release tag/commit of the code
nknd version v0.1-alpha-95-g51da

### Expected behaviour
What should happen?

### Actual behaviour
What is actually happening?
Generated 1.7GB size log during 1 second with many "too many open files ..."

### Steps to reproduce
probabilistic

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
N/A

![image](https://user-images.githubusercontent.com/31470624/44523866-0cbe9f00-a70e-11e8-89ef-7ae8d2e38648.png)

**Comment by doraemon0** [comment]
This issue should be fixed in https://github.com/nknorg/nkn/pull/232.
