### ISSUE TITLE
make test is failing currently

### ISSUE THREAD

**Issue by ansrivas** [nknorg/nkn#258]
### Description of the issue
`make test` is failing currently. Turns out that porpackage_test.go:48 is failing where we are trying to create NewPorPackage with a given transaction. The test is trying to fetch `HeightByBlockHash` which is failing currently.

### Issue-Type (put a `x` sign in the square brackets)
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* OS: `Fedora 28`
* Go version:  `1.10.4`
* Release tag/commit of the code `79268403cc544eb0cf84357cc179a56540499787`

### Expected behaviour
Tests should pass.

### Actual behaviour
Tests are failing.

### Steps to reproduce
Just execute `make test`

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
The blockhash being provided to `height, err := Store.GetHeightByBlockHash(blockHash)` is all zeroes.

**Comment by abebeos** [comment]
@yilunzhang , this issue can be closed.

follow-up: #888
