### ISSUE TITLE
Parse confidential via command-line.

### ISSUE THREAD

**Issue by ZihanTang** [nknorg/nkn#261]
### Description of the issue
Describe the issue you are experiencing.

### Issue-Type (put a `x` sign in the square brackets)
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* OS ubuntu 16.04
* Go version 1.10
* Release tag/commit of the code 79268403cc544eb0cf84357cc179a56540499787

### Expected behaviour
What should happen?
nknd/nknc seems only accept password via interact with human, could we have an option to parse it from command-line, i.e. `nknd --password xxxxxxxx`. It will be much convenient to start/restart nknd from scratch when using docker.

### Actual behaviour
What is actually happening?
Currently, user must enter their confidential from command-line.
### Steps to reproduce
1. Provide detailed steps
Run command `nknd`
2. how to reproduce this issue
Run command `nknd`

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

**Comment by yilunzhang** [comment]
Actually both nknd and nknc accept password through -p parameter. E.g. nknd -p 1.

However, we didn't document this usage intentionally because your password will then be recorded in plain text in the cmd history, which is very dangerous. That means whoever has access to your wallet.dat and cmd history can transfer all your token to anywhere.

**Comment by yilunzhang** [comment]
Maybe we should write about this somewhere in doc/readme.

**Comment by ZihanTang** [comment]
Thanks, I'll close this one.

**Comment by anoane** [comment]
> Actually both nknd and nknc accept password through -p parameter. E.g. nknd -p 1.
> 
> However, we didn't document this usage intentionally because your password will then be recorded in plain text in the cmd history, which is very dangerous. That means whoever has access to your wallet.dat and cmd history can transfer all your token to anywhere.

Indeed it is very dangerous. This option should be discouraged to the regular user, and it should not be available by default (there are many mechanisms to manage settings, and manual activation should display a big red warning).
I noticed from nkn.org some small introduction posts, and one of them is:
https://medium.com/nknetwork/how-to-set-up-a-nkn-miner-on-windows-10-and-run-it-as-a-automatic-service-63e5b7a6b792

Which is suggesting to use: .\nknd.exe -p YOUR_WALLET_PASSWORD

This command should be removed from the tutorial and it should be disabled by default.
It's very unsafe.

**Comment by yilunzhang** [comment]
Agreed. That's why -p option is hidden in help menu so people wouldn't find it unless they knew it.

We have asked a few tutorials to remove the -p part but I think we missed this one. @CrackDavid Do we have a safer option in windows?

**Comment by ZihanTang** [comment]
What's the safe way to parse confidential in linux? Currently I used `-p option` in ansible script for miners and transfer tNKNs to a Neo wallet periodically.

**Comment by ZihanTang** [comment]
It seems like that cloud image script store password in local file `wallet.pswd `.  https://github.com/nknorg/nkn-cloud-image/blob/master/scripts/launch_node.sh

I think it make no difference to parse password via command directly or via cat file trick.

**Comment by yilunzhang** [comment]
The difference is that you can set file permission to protect wallet.pswd. If you have control of the system, environment variable may be a good choice

**Comment by ZihanTang** [comment]
sounds good

**Comment by CrackDavid** [comment]
> Agreed. That's why -p option is hidden in help menu so people wouldn't find it unless they knew it.
> 
> We have asked a few tutorials to remove the -p part but I think we missed this one. @CrackDavid Do we have a safer option in windows?

Good question - have to take a look on it. All my other tutorials use the -p flag too so maybe we should talk in discord about a best practice - I'm not a fan of using a password file either ;)
