### ISSUE TITLE
[Raspberry pi] node crashes and loses sync after "Get block header error: leveldb: not found"

### ISSUE THREAD

**Issue by CrackDavid** [nknorg/nkn#288]
### Description of the issue
My local rasperry pi gets regularly out of sync with the testnet. After that it shows following warnings and doesn't participate to the network at all:

`AddVoteForBlock: block: 4e5c54f4b4805ecd3f0c1a95f4ef7f168889bf115318d10df456453fbc654885 doesn't exist, cache vote only `

Problem starts round about 15 Minutes after starting the node with a fresh Chain. Node crashes with:

```
2018/09/13 11:04:01.669527 [WARN ] GID 12633, receive block which height is invalid, consensus height: 44578, received block height: 44579, hash: 452da64319ad18d55e986cd4134f09f78581d453dbb2b142cdd8ba2fad8636c3
2018/09/13 11:04:02.900955 [ERROR] GID 12817, Get block header error: leveldb: not found
2018/09/13 11:04:02.906263 [ERROR] GID 12740, state is different with neighbors, current voting height: 44580, neighbor height: 44581 (9/16), exits.
```

When it gets restarted it is out of sync. 

Hope that helps!

### Issue-Type (put a `x` sign in the square brackets)
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
Raspbian stretch lite Kernel version 4.14
1.11 arm
v0.3.6-alpha-dirty

### Expected behaviour
Not getting out of sync.

### Actual behaviour
Described above.

### Steps to reproduce
1. Provide detailed steps
2. how to reproduce this issue

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
For more information you can reach me on Discord (ChrisT).

**Comment by yilunzhang** [comment]
This is a known issue. Most of the times node should be able to recover itself simply by restarting. So restarting doesn't work for you?

Also, we plan to resolve it automatically (instead of just quit) when we add block rollback functions.

**Comment by CrackDavid** [comment]
No, restarting doesn’t work as intended there. There is that ‚Cache vote only‘ message for all further blocks.

**Comment by CrackDavid** [comment]
Never happened since the latest update - I think issue can be closed.
