### ISSUE TITLE
Node height = 0 when getting syncstate for node

### ISSUE THREAD

**Issue by 98farhan94** [nknorg/nkn#308]
### Description of the issue
`./nknc info -s` gives node height 0.

### Issue-Type (put a `x` sign in the square brackets)
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* OS Ubuntu 16.04
* Go version 1.8
* Release tag/commit of the code 980bbfc023127c31970f30d0e6d34278ca7cd17c

### Expected behaviour
What should happen?
I think it should give a height count.

### Actual behaviour
What is actually happening?
It is giving a height count, but height count is always 0.

### Steps to reproduce
1. Provide detailed steps: `./nknc info -s`
2. how to reproduce this issue: follow step 1

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.
![screen shot 2018-09-25 at 11 12 22 pm](https://user-images.githubusercontent.com/5463117/46032160-7e787700-c118-11e8-9ca8-b82a375ad875.png)

**Comment by doraemon0** [comment]
The local node state is not being updated. Will fix it.

**Comment by gdmmx** [comment]
@98farhan94 PR #339 has fixed it.
It will be contained in next release.
