### ISSUE TITLE
./nknc does not transfer - INVALID METHOD (-42001)

### ISSUE THREAD

**Issue by alexandergalitski** [nknorg/nkn#310]
### Description of the issue
nknc does not transfer - INVALID METHOD (-42001)
```Log: [WARN ] GID 910315, HTTP JSON RPC Handle - No function to call for  sendtoaddress```

### Issue-Type (put a `x` sign in the square brackets)
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* Linux
* go version go1.10.3 linux/amd64
* 52c83549153df70ba6915dd34e6a0c1b31d4b6a1

### Expected behaviour
should receive tx id

### Actual behaviour
```
{
        "error": {
                "code": -42001,
                "message": "INVALID METHOD"
        },
        "id": 0,
        "jsonrpc": "2.0"
}
```

### Steps to reproduce
./nknc asset -t -p MYPASSWORD -a 4945ca009174097e6614d306b66e1f9cb1fce586cb857729be9e1c5cc04c9c02 -v 10 --to RECEIVINGADDRESS

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

**Comment by NoelBright** [comment]
the api of transfer used by nknc is disabled by default.
