### ISSUE TITLE
API features request

### ISSUE THREAD

**Issue by thesheepman** [nknorg/nkn#329]
### Description of the issue
`getnodestate `— would be nice to add the property of  `latestblockheight` and `getversion`, in order not to send 3 different requests and do not overload the frontend.

### Issue-Type (put a `x` sign in the square brackets)
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement

**Comment by gdmmx** [comment]
Implement in PR #339 @thesheepman 
It will be contained in next release.
