### ISSUE TITLE
Add log rotation function

### ISSUE THREAD

**Issue by asluchevskiy** [nknorg/nkn#376]
### Description of the issue
Most of unix daemons have a log rotation function by receiving HUP unix signal. Usially, it is not necessary to restart the whole daemon if I want only to rotate the log file, for example using logrotate.

### Issue-Type (put a `x` sign in the square brackets)
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Expected behaviour
What should happen? When receive HUP unix signal, nknd will close current log file and start new one.

### Actual behaviour
What is actually happening? Nothing.

**Comment by abebeos** [comment]
@yilunzhang , maybe after 5 years its time to either close as "wontfix", or at least look if the request is valid (and place a "casual bounty" on it, no bounty-systems nothing, just a label or a prefix so someone possibly picks it up. I see in the chat always people asking, so, just let them do something.

**Comment by yilunzhang** [comment]
Will close for now because we have implemented something similar: nknd will now automatically rotate log file and limit the size of (single and total) log file.
