### ISSUE TITLE
Adding Node public key in getnodestate-RPC

### ISSUE THREAD

**Issue by CrackDavid** [nknorg/nkn#389]
### Description of the issue
Hence we can parse the public key of the used nodes from the transaction payload it would be nice to get the node’s public key from the getnodestate RPC call.

In combination with the nknx nodecrawler we could then backtrace the way packets are relayed based on the geographic position and also create more „node utilization“ statistics.

### Issue-Type (put a `x` sign in the square brackets)
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement

### Checklist
- [ ] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* OS
* Go version
* Release tag/commit of the code

### Expected behaviour
What should happen?

### Actual behaviour
What is actually happening?

### Steps to reproduce
1. Provide detailed steps
2. how to reproduce this issue

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

**Comment by yilunzhang** [comment]
@gdmmx
