### ISSUE TITLE
Move to Go Modules

### ISSUE THREAD

**Issue by trueinsider** [nknorg/nkn#457]
Glide wasn't maintained since Sep 26, 2018 and Go 1.13 scheduled for August 2019 will deprecate GOPATH and use Go Modules by default. Moving forward we should stop using glide and start using modules.

**Comment by yilunzhang** [comment]
Agree. For now we have 2 options that can smoothly migrate to Go Module:

1. Change to Go module now and ask users to move code outside of GOPATH or set GO111MODULE=on in Makefile
2. Wait for Go 1.13 so GO111MODULE is by default ON

What's your opinion towards it. And also @dreamfly281 @NoelBright @gdmmx

**Comment by trueinsider** [comment]
There is quite a few repositories that need to be transferred to modules, so I think we can go ahead and start transferring them all in branches. And after that we can think if it should be merged now or when 1.13 is released.

**Comment by yilunzhang** [comment]
Migrated to Go Modules in #555
