### ISSUE TITLE
1/3 of nodes stops syncing blocks

### ISSUE THREAD

**Issue by zero24x** [nknorg/nkn#581]
### Description of the issue
Describe the issue you are experiencing.

### Issue-Type (put a `x` sign in the square brackets)
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* OS: Ubuntu 18.04.
* Go version: 1.12.6
* Release tag/commit of the code: 1.0.0.1b

### Expected behaviour
What should happen?

NKN should sync to latest block

### Actual behaviour
What is actually happening?

1 node if stuck syncing, block height is 0 event after stopping, removing ChainDB and even wallet.json files!

### Steps to reproduce
1. Provide detailed steps
2. how to reproduce this issue

Not sure how to reproduce, about 1/3 of nodes fail syncing.

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

> 
> 2019/07/07 05:40:52.309185 [INFO ] GID 107, Load remote node a028935c5761253a0b435bcb5b0b7ebbd361fd18a742a59e92b38654b5c49d67@tcp://60.189.211.204:30001<60.189.211.204:30001> from list
> 2019/07/07 05:40:52.309917 [INFO ] GID 107, Load remote node a02e05ee073d5e5cf81943b40cc94b9854cebcc67ad0b139241bc940d9efb02e@tcp://60.189.35.12:30001<60.189.35.12:30001> from list
> 2019/07/07 05:40:52.310510 [INFO ] GID 107, Load remote node <121.236.241.49:30001> from list
> 2019/07/07 05:40:52.310750 [INFO ] GID 107, Load remote node a03e6b8b1f8542e6d847dccf46a05601ee910a2abc0808e191288d898fb66c53@tcp://35.203.26.0:30001<35.203.26.0:30001> from list
> 2019/07/07 05:40:52.311315 [INFO ] GID 107, Load remote node a04aa9bdf8affd2ca9c77d8c917e888c088ff370adde5b91aefead1b767d5097@tcp://183.153.145.215:30001<183.153.145.215:30001> from list
> 2019/07/07 05:40:52.312022 [INFO ] GID 107, Another goroutine is connecting to 117.28.73.128:30001
> 2019/07/07 05:40:52.358840 [INFO ] GID 1, Another goroutine is connecting to 180.119.141.13:30001
> 2019/07/07 05:40:52.559014 [INFO ] GID 230, Set min verifiable height to 4
> 2019/07/07 05:40:52.593165 [INFO ] GID 107, Load remote node <115.216.198.99:30001> from list
> 2019/07/07 05:40:53.555785 [INFO ] GID 101, Remote node connect from 165.22.158.10:39296 to local address 192.3.247.177:30001
> 2019/07/07 05:40:53.780016 [INFO ] GID 101, Remote node connect from 180.108.208.78:56869 to local address 192.3.247.177:30001
> 2019/07/07 05:40:55.015391 [INFO ] GID 101, Remote node connect from 134.209.48.183:33134 to local address 192.3.247.177:30001
> 2019/07/07 05:40:57.090570 [INFO ] GID 101, Remote node connect from 110.82.226.174:2292 to local address 192.3.247.177:30001
> 2019/07/07 05:40:57.439100 [INFO ] GID 101, Remote node connect from 3.8.93.246:34620 to local address 192.3.247.177:30001
> 2019/07/07 05:40:57.625176 [INFO ] GID 101, Remote node connect from 114.220.154.144:27782 to local address 192.3.247.177:30001
> 2019/07/07 05:40:58.968546 [INFO ] GID 101, Remote node connect from 104.154.98.27:46144 to local address 192.3.247.177:30001
> 2019/07/07 05:40:59.659742 [INFO ] GID 101, Remote node connect from 40.86.185.36:55040 to local address 192.3.247.177:30001
> 2019/07/07 05:41:00.398326 [INFO ] GID 101, Remote node connect from 18.179.94.49:51716 to local address 192.3.247.177:30001
> 2019/07/07 05:41:01.005685 [INFO ] GID 101, Remote node connect from 58.209.18.34:14909 to local address 192.3.247.177:30001
> 2019/07/07 05:41:01.327586 [INFO ] GID 101, Remote node connect from 121.224.117.51:33420 to local address 192.3.247.177:30001
> 2019/07/07 05:41:02.559195 [WARN ] GID 227, Handle proposal error: Wait for proposal timeout
> 2019/07/07 05:41:02.750226 [INFO ] GID 101, Remote node connect from 68.183.201.246:59264 to local address 192.3.247.177:30001
> 2019/07/07 05:41:04.050410 [INFO ] GID 101, Remote node connect from 68.183.157.184:43262 to local address 192.3.247.177:30001
> 2019/07/07 05:41:05.165749 [INFO ] GID 101, Remote node connect from 115.216.199.145:57408 to local address 192.3.247.177:30001
> 2019/07/07 05:41:05.992486 [INFO ] GID 101, Remote node connect from 117.80.20.106:1394 to local address 192.3.247.177:30001
> 2019/07/07 05:41:07.445750 [INFO ] GID 101, Remote node connect from 121.236.65.29:24329 to local address 192.3.247.177:30001
>

**Comment by zero24x** [comment]
stopping node, restarting after 1 day (& removing ChainDB folder helped) but i guess we still have an issue with nodes getting out of sync sometimes / was it an attack?

**Comment by yilunzhang** [comment]
It's not an attack, but it seems to be related to the node quality in mainnet. We are still trying to reproduce similar problem in our internal environment but it's very difficult to reproduce...

**Comment by zero24x** [comment]
looks all fine to me now, nodes are in sync again since running the recently 1.0.4, thanks for helping!
