### ISSUE TITLE
 Update successors error: neighbor list is empty

### ISSUE THREAD

**Issue by yangjian102621** [nknorg/nkn#590]
Well, i can not start the node with an error :  Update successors error: neighbor list is empty
when i upgrade the `nknd`  to version v1.0.3-beta.

Note: i had set up port forwarding on my router, and it work well in version v1.0.2-beta.

**Comment by yilunzhang** [comment]
It would be better if you can put the full log. This is typically caused by you Internet, e.g., your router/os firewall cut all incoming connections.

**Comment by yangjian102621** [comment]
@yilunzhang i got the problem, it because my BeneficiaryAddr is in use at another node.
i create a new wallet and replace the BeneficiaryAddr,  it works.
Thanks.

**Comment by yilunzhang** [comment]
BeneficiaryAddr is designed to be shared among nodes, but wallet.json must be unique for each node. You mean you were sharing wallet.json between different nodes right?

**Comment by yangjian102621** [comment]
@yilunzhang 
Yep, i copied the wallet json file, because i can not find the way  to export and inport wallet.

**Comment by yilunzhang** [comment]
I see. That’s the reason you got the error. Each node in the network must have unique wallet.json, but they can use the same beneficiary address to share mining reward.

**Comment by yangjian102621** [comment]
@yilunzhang 
So, is there any way to export and import the wallet?

**Comment by yilunzhang** [comment]
The wallet is stored in wallet.json. You just need it together with the password you used to create to wallet. If you use the onel-click miner, the password is stored in wallet.pswd.

**Comment by yangjian102621** [comment]
@yilunzhang 
OK, i got it

**Comment by markg85** [comment]
WHAT?!

Please.... DESCRIBE this somewhere!
I had this very error and thought something was wrong with the firewall. So i tried different droplets, played with loads of different firewall options. All with tons of frustration just to figure out that the WALLET HAD TO BE UNIQUE.... Men... please.. really, describe that somewhere clearly visible when making a miner.

**Comment by yilunzhang** [comment]
> WHAT?!
> 
> Please.... DESCRIBE this somewhere!
> I had this very error and thought something was wrong with the firewall. So i tried different droplets, played with loads of different firewall options. All with tons of frustration just to figure out that the WALLET HAD TO BE UNIQUE.... Men... please.. really, describe that somewhere clearly visible when making a miner.

It is always shown, very explicitly, in bold text, with an [IMPORTANT] mark, in the github readme 😂

**Comment by markg85** [comment]
> > WHAT?!
> > Please.... DESCRIBE this somewhere!
> > I had this very error and thought something was wrong with the firewall. So i tried different droplets, played with loads of different firewall options. All with tons of frustration just to figure out that the WALLET HAD TO BE UNIQUE.... Men... please.. really, describe that somewhere clearly visible when making a miner.
> 
> It is always shown, very explicitly, in bold text, with an [IMPORTANT] mark, in the github readme

Perhaps. But not in the guide that i followed for digitalocean https://medium.com/nknetwork/one-click-to-build-a-new-kind-of-network-node-on-digital-ocean-e5d11319a892. Or any other guides that show you how to setup a miner! (or i'm blind?)

Regardless, i had to read that guide like 6 times to make sense to me. It's written... well.. poorly. It's written with a sense that you know what NKN is and how it works. It doesn't explain stuff that you definitely want to know if you're just starting with it.

**Comment by yilunzhang** [comment]
> Perhaps. But not in the guide that i followed for digitalocean https://medium.com/nknetwork/one-click-to-build-a-new-kind-of-network-node-on-digital-ocean-e5d11319a892. Or any other guides that show you how to setup a miner! (or i'm blind?)
> 
> Regardless, i had to read that guide like 6 times to make sense to me. It's written... well.. poorly. It's written with a sense that you know what NKN is and how it works. It doesn't explain stuff that you definitely want to know if you're just starting with it.

The guide you are referring to is for DO one-click, which generates a unique wallet for you. It's designed such that people who don't understand how NKN works can still set up a miner, but we never ask or recommend you to change the generated wallet.json at all (and you are not supposed to). If you follow the guide and use BeneficiaryAddress instead, you shouldn't get into any of these problems. But if you want to use the hard way and build NKN from source, we assume you at least read the github readme.

**Comment by markg85** [comment]
> > Perhaps. But not in the guide that i followed for digitalocean https://medium.com/nknetwork/one-click-to-build-a-new-kind-of-network-node-on-digital-ocean-e5d11319a892. Or any other guides that show you how to setup a miner! (or i'm blind?)
> > Regardless, i had to read that guide like 6 times to make sense to me. It's written... well.. poorly. It's written with a sense that you know what NKN is and how it works. It doesn't explain stuff that you definitely want to know if you're just starting with it.
> 
> The guide you are referring to is for DO one-click, which generates a unique wallet for you. It's designed such that people who don't understand how NKN works can still set up a miner, but we never ask or recommend you to change the generated wallet.json at all (and you are not supposed to). If you follow the guide and use BeneficiaryAddress instead, you shouldn't get into any of these problems. But if you want to use the hard way and build NKN from source, we assume you at least read the github readme.

I definitely want to take the easy route, not the hard route.
But from that article, it wasn't clear to me that just setting the BeneficiaryAddress would make it work how one does expect it would. 

The wording of the copying in that article is what threw me off completely in the wrong direction.
To quote:
> Copy **your** wallet.json (includes your wallet ID) file to your computer

which i interpreted as copying **my** wallet to the server. The intention however (in hindsight) was exactly the way that didn't make sense to me. Copy it **from the server to my computer**. The article does that for the wallet.json and wallet.pswd files. I get it **now**, but that's some wonky wording that's easy to throw you off completely.

Also, please note that the article is from before version 1.0 was released. Before that time the copying of the wallet (from your computer to the server) worked. 1.0 changed that to require 1 unique wallet per miner, which i only know because i've read a load of nkn release notes :).
