### ISSUE TITLE
What causes this?

### ISSUE THREAD

**Issue by huming-china** [nknorg/nkn#597]
6, Load remote node <207.154.254.161:30001> from list
2019/07/28 15:39:51.764204 [INFO ] GID 81, Received stop message from remote node 2ec6f7da70bae80e41f456bc7fca4f6bbdb409f371cdaa4e3a622c5b08f8f6db@tcp://14.145.138.76:30001<14.145.138.76:30001>
2019/07/28 15:39:51.764290 [INFO ] GID 81, Remote node 2ec6f7da70bae80e41f456bc7fca4f6bbdb409f371cdaa4e3a622c5b08f8f6db@tcp://14.145.138.76:30001<14.145.138.76:30001> stops
2019/07/28 15:39:52.334170 [INFO ] GID 81, Received stop message from remote node 2eca4e6b65938cb061a2616d469759d322f89e2be6ce778e0058403370274c1e@tcp://134.209.196.232:30001<134.209.196.232:30001>
2019/07/28 15:39:52.334252 [INFO ] GID 81, Remote node 2eca4e6b65938cb061a2616d469759d322f89e2be6ce778e0058403370274c1e@tcp://134.209.196.232:30001<134.209.196.232:30001> stops
2019/07/28 15:39:52.340027 [WARN ] GID 1449, Ping <207.154.254.161:30001> error: Wait for reply timeout
2019/07/28 15:39:52.586064 [WARN ] GID 1462, Remote node <207.154.254.161:30001> stops because of error: Read msg len error: read tcp 192.168.16.4:42410->207.154.254.161:30001: read: connection reset by peer
2019/07/28 15:39:52.942390 [WARN ] GID 1488, Ping <54.39.247.210:30001> error: Wait for reply timeout
2019/07/28 15:39:53.173487 [INFO ] GID 81, Received stop message from remote node 2ec3bd0bb6fc4221cf38ddbfe0a533384ddd02565955bb18162fbec26438e8a0@tcp://167.71.181.78:30001<167.71.181.78:30001>
2019/07/28 15:39:53.173590 [INFO ] GID 81, Remote node 2ec3bd0bb6fc4221cf38ddbfe0a533384ddd02565955bb18162fbec26438e8a0@tcp://167.71.181.78:30001<167.71.181.78:30001> stops
2019/07/28 15:39:53.750173 [INFO ] GID 81, Received stop message from remote node 2eb63230b60f34c5fbae0b7ce39e999e5ec2649c1718becc6919575e327ec474@tcp://171.211.94.246:30001<171.211.94.246:30001>
2019/07/28 15:39:53.750256 [INFO ] GID 81, Remote node 2eb63230b60f34c5fbae0b7ce39e999e5ec2649c1718becc6919575e327ec474@tcp://171.211.94.246:30001<171.211.94.246:30001> stops
2019/07/28 15:39:54.367518 [INFO ] GID 81, Received stop message from remote node 2ec3bd0bb6fc4221cf38ddbfe0a533384ddd02565955bb18162fbec26438e8a0@tcp://167.71.181.78:30001<167.71.181.78:30001>
2019/07/28 15:39:54.367616 [INFO ] GID 81, Remote node 2ec3bd0bb6fc4221cf38ddbfe0a533384ddd02565955bb18162fbec26438e8a0@tcp://167.71.181.78:30001<167.71.181.78:30001> stops
2019/07/28 15:39:54.838865 [WARN ] GID 1552, Ping <134.209.196.232:30001> error: Wait for reply timeout
2019/07/28 15:39:55.266532 [INFO ] GID 81, Received stop message from remote node 2ec6f7da70bae80e41f456bc7fca4f6bbdb409f371cdaa4e3a622c5b08f8f6db@tcp://14.145.138.76:30001<14.145.138.76:30001>
2019/07/28 15:39:55.266616 [INFO ] GID 81, Remote node 2ec6f7da70bae80e41f456bc7fca4f6bbdb409f371cdaa4e3a622c5b08f8f6db@tcp://14.145.138.76:30001<14.145.138.76:30001> stops
2019/07/28 15:39:55.726108 [WARN ] GID 408, Local node has no inbound neighbor, it's possible that local node is unreachable from outside, e.g. behind firewall or NAT.
2019/07/28 15:39:56.428620 [WARN ] GID 243, Handle proposal error: Wait for neighbor vote timeout
2019/07/28 15:39:56.758274 [WARN ] GID 1733, Remote node 2eca4e6b65938cb061a2616d469759d322f89e2be6ce778e0058403370274c1e@tcp://134.209.196.232:30001<134.209.196.232:30001> stops because of error: Read msg len error: EOF
2019/07/28 15:39:56.796591 [INFO ] GID 81, Received stop message from remote node 2eca4e6b65938cb061a2616d469759d322f89e2be6ce778e0058403370274c1e@tcp://134.209.196.232:30001<134.209.196.232:30001>
2019/07/28 15:39:58.219557 [INFO ] GID 81, Received stop message from remote node 2eb63230b60f34c5fbae0b7ce39e999e5ec2649c1718becc6919575e327ec474@tcp://171.211.94.246:30001<171.211.94.246:30001>
2019/07/28 15:39:58.219633 [INFO ] GID 81, Remote node 2eb63230b60f34c5fbae0b7ce39e999e5ec2649c1718becc6919575e327ec474@tcp://171.211.94.246:30001<171.211.94.246:30001> stops
2019/07/28 15:39:58.488283 [INFO ] GID 81, Received stop message from remote node 2ec6f7da70bae80e41f456bc7fca4f6bbdb409f371cdaa4e3a622c5b08f8f6db@tcp://14.145.138.76:30001<14.145.138.76:30001>
2019/07/28 15:39:58.488391 [INFO ] GID 81, Remote node 2ec6f7da70bae80e41f456bc7fca4f6bbdb409f371cdaa4e3a622c5b08f8f6db@tcp://14.145.138.76:30001<14.145.138.76:30001> stops
2019/07/28 15:39:58.543876 [WARN ] GID 1506, Ping 2ebefa0d5d5fa2be64fdeeac5a1f40c17a963d851a4f9f8ee6aa3146595373d6@tcp://207.180.194.175:30001<207.180.194.175:30001> error: Wait for reply timeout
2019/07/28 15:39:58.765560 [ERROR] GID 1658, Error sending sync messge to node: Wait for reply timeout
2019/07/28 15:39:58.765653 [WARN ] GID 1658, Get consensus state from neighbor 2ebefa0d5d5fa2be64fdeeac5a1f40c17a963d851a4f9f8ee6aa3146595373d6 error: Wait for reply timeout
2019/07/28 15:39:58.942834 [WARN ] GID 1488, Ping <54.39.247.210:30001> error: Wait for reply timeout
2019/07/28 15:39:59.152330 [WARN ] GID 1700, Remote node 2ec4e51936844fe0c43c83f876073fb123acc246e95d40c416dc297befe45a12@tcp://207.154.254.161:30001<207.154.254.161:30001> stops because of error: Read msg len error: EOF
2019/07/28 15:39:59.185645 [INFO ] GID 81, Received stop message from remote node 2ec4e51936844fe0c43c83f876073fb123acc246e95d40c416dc297befe45a12@tcp://207.154.254.161:30001<207.154.254.161:30001>
2019/07/28 15:39:59.341609 [WARN ] GID 1778, Remote node <167.71.181.78:30001> stops because of error: Read msg len error: EOF
2019/07/28 15:39:59.558543 [INFO ] GID 81, Received stop message from remote node 2ec3bd0bb6fc4221cf38ddbfe0a533384ddd02565955bb18162fbec26438e8a0@tcp://167.71.181.78:30001<167.71.181.78:30001>
2019/07/28 15:39:59.864340 [INFO ] GID 81, Received stop message from remote node 2eca4e6b65938cb061a2616d469759d322f89e2be6ce778e0058403370274c1e@tcp://134.209.196.232:30001<134.209.196.232:30001>
2019/07/28 15:39:59.864442 [INFO ] GID 81, Remote node 2eca4e6b65938cb061a2616d469759d322f89e2be6ce778e0058403370274c1e@tcp://134.209.196.232:30001<134.209.196.232:30001> stops
2019/07/28 15:40:00.821537 [ERROR] GID 407, Update predecessor error: Wait for reply timeout
2019/07/28 15:40:01.487216 [INFO ] GID 81, Received stop message from remote node 2eb63230b60f34c5fbae0b7ce39e999e5ec2649c1718becc6919575e327ec474@tcp://171.211.94.246:30001<171.211.94.246:30001>
2019/07/28 15:40:01.487313 [INFO ] GID 81, Remote node 2eb63230b60f34c5fbae0b7ce39e999e5ec2649c1718becc6919575e327ec474@tcp://171.211.94.246:30001<171.211.94.246:30001> stops
2019/07/28 15:40:02.942269 [WARN ] GID 1489, Remote node <54.39.247.210:30001> stops because of error: Get node error: Wait for reply timeout
2019/07/28 15:40:02.975728 [INFO ] GID 81, Received stop message from remote node 2ec6f7da70bae80e41f456bc7fca4f6bbdb409f371cdaa4e3a622c5b08f8f6db@tcp://14.145.138.76:30001<14.145.138.76:30001>
2019/07/28 15:40:02.975816 [INFO ] GID 81, Remote node 2ec6f7da70bae80e41f456bc7fca4f6bbdb409f371cdaa4e3a622c5b08f8f6db@tcp://14.145.138.76:30001<14.145.138.76:30001> stops
2019/07/28 15:40:03.653059 [INFO ] GID 81, Received stop message from remote node 2ec3bd0bb6fc4221cf38ddbfe0a533384ddd02565955bb18162fbec26438e8a0@tcp://167.71.181.78:30001<167.71.181.78:30001>
2019/07/28 15:40:03.653160 [INFO ] GID 81, Remote node 2ec3bd0bb6fc4221cf38ddbfe0a533384ddd02565955bb18162fbec26438e8a0@tcp://167.71.181.78:30001<167.71.181.78:30001> stops
2019/07/28 15:40:03.851763 [INFO ] GID 81, Received stop message from remote node 2eca4e6b65938cb061a2616d469759d322f89e2be6ce778e0058403370274c1e@tcp://134.209.196.232:30001<134.209.196.232:30001>
2019/07/28 15:40:03.851877 [INFO ] GID 81, Remote node 2eca4e6b65938cb061a2616d469759d322f89e2be6ce778e0058403370274c1e@tcp://134.209.196.232:30001<134.209.196.232:30001> stops

**Comment by yilunzhang** [comment]
These are caused by your node disconnect with its neighbors. It's very normal in a p2p system and you can ignore them.
