### ISSUE TITLE
Typo: "Serverer" (should be: "server")

### ISSUE THREAD

**Issue by zero24x** [nknorg/nkn#601]
https://github.com/nknorg/nkn/blob/2c717c888a3d63ff450071142a8d0849c6b79f22/api/common/interfaces.go#L403

the same typo seems to existing in the whole file interfaces.go in many places, or is it on purpose written like that?

**Comment by yilunzhang** [comment]
It's actually on purpose: in golang many people like to add "er" suffix to interface name 😂
