### ISSUE TITLE
INTERNAL ERROR on new node after Fast Deploy

### ISSUE THREAD

**Issue by sorcer1122** [nknorg/nkn#623]
### Description of the issue
Describe the issue you are experiencing.

### Issue-Type (put a `x` sign in the square brackets)
- [ x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* OS ubuntu 16
* Go version 1.12.7
* Release tag/commit of the code

### Expected behaviour
What should happen?

The node should start syncing

### Actual behaviour
What is actually happening?
No blocks are syncing and there is an error in the log all the time.

### Steps to reproduce
1. Install the latest code of the node via fastdeploy
2. Check the log

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

2019/08/10 17:02:32.876010 [0;32m[INFO ][m GID 1, My IP address is x.x.x.x
2019/08/10 17:02:32.910349 [0;32m[INFO ][m GID 1, database Version: 1
2019/08/10 17:02:32.915003 [0;32m[INFO ][m GID 1, state root: (long string of random numbers)
2019/08/10 17:02:32.923956 [0;32m[INFO ][m GID 1, get no ID from local ledger
2019/08/10 17:02:33.433209 [0;32m[INFO ][m GID 1, GetID got resp: {"error":{"code":-45022,"data":null,"message":"INTERNAL ERROR, there is no ID in account"},"id":"1","jsonrpc":"2.0"} from http://mainnet-seed-0035.nkn.org:30003

2019/08/10 17:02:33.840712 [0;32m[INFO ][m GID 1, GetID got resp: {"error":{"code":-45022,"data":null,"message":"INTERNAL ERROR, there is no ID in account"},"id":"1","jsonrpc":"2.0"} from http://mainnet-seed-0013.nkn.org:30003

2019/08/10 17:02:34.039211 [0;32m[INFO ][m GID 1, GetID got resp: {"error":{"code":-45022,"data":null,"message":"INTERNAL ERROR, there is no ID in account"},"id":"1","jsonrpc":"2.0"} from http://mainnet-seed-0020.nkn.org:30003

2019/08/10 17:02:34.363051 [0;32m[INFO ][m GID 1, GetNonceByAddr got resp: {"id":"1","jsonrpc":"2.0","result":{"currentHeight":154254,"nonce":0,"nonceInTxPool":1}} from http://mainnet-seed-0008.nkn.org:30003

And so on...

**Comment by yilunzhang** [comment]
This is because too many nodes are trying to join the network for free while the network has limited free txn quota. See https://forum.nkn.org/t/joining-the-network-instantly-by-paying-10-8-nkn/1609 for information about how to join immediately by paying a tiny amount of fee

**Comment by sorcer1122** [comment]
It would be nice to add this link to the readme.md

**Comment by yilunzhang** [comment]
Will do!

**Comment by yilunzhang** [comment]
The new GenerateID mechanism now requires node to solve a crypto puzzle before joining (for the first time) and should be quite effective against DDoS attacks.

**Comment by yilunzhang** [comment]
Close this issue because it should have been resolved by the new crypto puzzle mechanism. Free feel to re-open it if the problem still persists.
