### ISSUE TITLE
Windows version does not work

### ISSUE THREAD

**Issue by whotheff** [nknorg/nkn#667]
### Description of the issue
It says: "error: cannot decrypt message: no shared key yet"
after I upgraded to 1.1.2

### Issue-Type (put a `x` sign in the square brackets)
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* OS Windows
* Go version
* Release tag/commit of the code 1.1.2 Beta

### Expected behaviour
What should happen?
start
### Actual behaviour
What is actually happening?
Stop
### Steps to reproduce
1. Provide detailed steps
2. how to reproduce this issue

Run under windows

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.
adding to config.json:

   "HttpWssCert":"certs/_.ipv4.nknlabs.io.cert",
   "HttpWssKey":"certs/_.ipv4.nknlabs.io.key",
   "HttpsJsonCert":"certs/_.ipv4.nknlabs.io.cert",
   "HttpsJsonKey":"certs/_.ipv4.nknlabs.io.key",
   "MaxGetIDSeeds": 32
(there should be an underscore before the .ipv4) 

Windows does not support * symbol in file names

by advice of Yulin fixed it, although the value 32 was randomly chosen by me.

**Comment by yilunzhang** [comment]
Fixed in #668
