### ISSUE TITLE
AddBlock Error: LevelDB Not Found

### ISSUE THREAD

**Issue by joesixpack** [nknorg/nkn#709]
### Description of the issue
Getting AddBlock error in both Docker and binaries.

### Issue-Type (put a `x` sign in the square brackets)
- [x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x] Running latest version of code.
- [x] This issue has not been reported earlier.

### Your environment
* OS: Ubuntu 16.04 LTS
* Go version: 1.13.4
* Release tag/commit of the code: v1.17-beta

### Expected behaviour
Blocks added succesfully.

### Actual behaviour
AddBlock error.

### Steps to reproduce
Starts nknd as per normal.

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
![image](https://user-images.githubusercontent.com/23145642/81462610-afc87e00-9168-11ea-8a5c-219bd6741491.png)

**Comment by yilunzhang** [comment]
You local database seems corrupted. Did you modify contents in ChainDB somehow, especially when nknd is running? For example, unzipping a ChainDB snapshot while nknd is running will lead to this issue.

**Comment by joesixpack** [comment]
Hmm nope, basically just installed the latest update.  But I've removed ChainsDB and resynced.  Seems OK now.
