### ISSUE TITLE
Creating generate ID txn. This process may take quite a few minutes...

### ISSUE THREAD

**Issue by joesixpack** [nknorg/nkn#716]
Been over 45 minutes, how long is this supposed to take?

**Comment by yilunzhang** [comment]
It's a mini PoW puzzle, the time depends on your CPU power and (probably more importantly) your luck. It can take from 10+ mins to somewhere like a few hours if you are not in luck.

**Comment by zbruceli** [comment]
Known feature for enhancing security, not a bug.
