### ISSUE TITLE
Use ed25519 instead of p256

### ISSUE THREAD

**Issue by yilunzhang** [nknorg/nkn#74]
There are several reasons to switch:
1. Better performance
2. Better compatibility with VRF
3. Prepare to switch to deterministic signature (e.g. XEdDSA) as the RNG could be (and has been) the weak point in security

**Comment by NoelBright** [comment]
the curve25519 and ed25519 are different things:

curve 25519 is used for elliptic curve Diffie-Hellman.
ed25519 us used for EdDSA signature.

edwards25519 curve is birationally equivalent to Curve25519. Meaning that you can transform a point (u,v) of Curve25519 to a point (x,y) of the curve edwards25519 with the transformation:

y=(u−1)/(u+1).

So we can use the uniform key format of P256r1 for both P256r1 and Ed25519. When using Ed25519, we just need transfer the keys to the format of Ed25519.

**Comment by NoelBright** [comment]
done #461
