### ISSUE TITLE
wildcard certificate in domain handling

### ISSUE THREAD

**Issue by markg85** [nknorg/nkn#747]
Hi,

NKN allows you to set certificate keys to be used for HTTPS and the domain under which it's reachable.
Setting the domain is done by adding `HttpWssDomain` and `HttpsJsonDomain` with a domain value in your config.js. In my case this is set to `nkn.sc2.nl`.

Next the certificate keys can be set by adding:
`HttpWssCert` and `HttpsJsonCert` with your public key certificate file.
`HttpWssKey` and `HttpsJsonKey` with your private certificate file.

**If your certificate is a wildcard certificate, you'll get an error from NKN**

In my case my certificate is for `*.sc2.nl`. The NKN code checks for `nkn.sc2.nl` to be equal to `*.sc2.nl` which it isn't and thus it gives you an error like: `inconsistent domain names`.

This should probably be handled gracefully in the NKN codebase to allow for wildcards in the certificate.

Cheers,
Mark

**Comment by yilunzhang** [comment]
Fixed in #928
