### ISSUE TITLE
Syncing NKN node

### ISSUE THREAD

**Issue by Franiebones** [nknorg/nkn#758]
I went through digital ocean last night to setup the process for mining NKN, I setup my node last night and went through the Generating ID phase and now it's stuck on the SYNCING phase, Does this usually take a long time because I went to bed around 11:30pm last night and woke up around 5am to see that the process isn't done yet. I hope that everything is running smoothly and that it's normal for it to take this long. If not, since I'm brand new this I might need someone help to finish setting it up. would someone be able to walk me through the process ?

**Comment by Karasur** [comment]
Its better to download latest pruned ChainDB and restart node after.
Check this [manual ](https://forum.nkn.org/t/tutorial-how-to-manually-download-latest-pruned-chaindb-google-cloud/2723) (file size is 12GB)

**Comment by Franiebones** [comment]
Hey thanks for the response back and sorry I didn't get back to you earlier. I was at work ( Amazon ) and ended up taking some PTO so I could run home and take care of this.  While I was at work, it seemed to sync and everything is running smoothly now and is telling me that I'm mining which is great news, tell me more about that Chain DB because I'm under the expression that you can add more then 1 node on your computer and I don't know if I'm correct since I'm a newcomer in the space. I trade crypto, and invest in certain projects as well as stack crypto but as for mining, this is new. Is that possible that I can run than one node on the same device?..

**Comment by Franiebones** [comment]
I went and read that tutorial about Chain DB and that's for google cloud, I just now signed up for it and I'm checking it out now. Is there a way I can bring my node to that cloud?.. or how do I go about getting ChainDB through google cloud isn't in the cloud?

**Comment by yilunzhang** [comment]
Syncing is expected to take a long time because node will download all blockchain history, verify they are correct and compress local database to save spaces. For normal CPU/Disk it might even take 2-3 days. Each node only needs to do that once.

Many people chose to use chain snapshot to save that 2-3 days syncing time. If you decide to use that, the tutorial Karasur sent should work regardless of where your node is (aws, google cloud, digital ocean, etc).

**Comment by Franiebones** [comment]
Ok, perfect. My node finally started mining around 1pm so it took about 8 hours in all which was shorter than expected after all the research I did. I'm not experienced with chain snapshot or ChainDB but I'm learning as I go and I'm definitely excited about it. Can you run more than one node on a single device or do you need multiple devices in order to run more than one node?

**Comment by yilunzhang** [comment]
Each nkn node must have a unique public IP address, so for most people that's one node per device.

**Comment by Franiebones** [comment]
Ok got it, now if I owned my own business, etc. and had multiple IP then I could.  Ok, thank you for your help and I will let everyone I know in the crypto community about this project and get some others on board to help with the network.

**Comment by yilunzhang** [comment]
> now if I owned my own business, etc. and had multiple IP then I could.

Yes, just like how VPS create cloud virtual machines.

Thanks for your support!
