### ISSUE TITLE
How to check that the node has started?

### ISSUE THREAD

**Issue by ArtemiyFirsov** [nknorg/nkn#759]
### Description of the issue
Hello!

I am trying to understand if my NKN node installation is working properly.
I am seeing a bunch of messages in the console, mostly INFO, some errors and warnings with "Wait reply timeout"

I have a router with UPnP, and additionally, I have configured the port forwarding.
Using Docker version

Node version: v2.0.8
Node status:chain db sync ​started

How can I understand that everything is OK?

​### Issue-Type (put a `x` sign in the square brackets)
- [ ] bug report
- [ ] feature request
- [X] Documentation improvement

### Checklist
- [X] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* Windows 10
* Docker release pulled on 04/10/2021

### Expected behaviour
What should happen?

### Actual behaviour
---

### Steps to reproduce
---

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
---

**Comment by bufrr** [comment]
Hello, you can check node status using nstatus.org.

**Comment by yilunzhang** [comment]
It looks good based your description.

> I am seeing a bunch of messages in the console, mostly INFO, some errors and warnings with "Wait reply timeout"

Those warning are mostly for debug and can be safely ignored.

> Node status:chain db sync ​started

This means your node is syncing blocks and it's a necessary stage.

As bufrr suggested, you can use http://nstatus.org or nknx.org to check your node status.
