### ISSUE TITLE
I am installing nkn v2.0.8 on my linux server and i want a link for jason config file to install

### ISSUE THREAD

**Issue by rajakhan12** [nknorg/nkn#761]
Hi,

To setup NKN Mining

I was following this youtube video step below

https://www.youtube.com/watch?v=NEoshg_jf4I&t=157s

and on step time 2:37 he added a link https://raw.githubusercontent.com/nknorg/nkn/ma..../configure.mining.jason
it was something like that and i can see that link properly , where i can get that link 

Regards

Tanveer

**Comment by bufrr** [comment]
https://github.com/nknorg/nkn/blob/master/config.mainnet.json

**Comment by rajakhan12** [comment]
thanks you ..... what is different between  config.testnet and config.mainnet ?

**Comment by bufrr** [comment]
> thanks you ..... what is different between config.testnet and config.mainnet ?

`testnet.json` is the config file for testnet, which was no longer exists.

**Comment by rajakhan12** [comment]
I done that step .. see terminal screen below , what shoud i do next

root@NLDW1-4-17-14:~/linux-amd64# ls
default.json  nknc  nknd  web
root@NLDW1-4-17-14:~/linux-amd64# wget https://github.com/nknorg/nkn/blob/master/config.mainnet.json
--2021-04-11 17:42:54--  https://github.com/nknorg/nkn/blob/master/config.mainnet.json
Resolving github.com (github.com)... 140.82.121.4
Connecting to github.com (github.com)|140.82.121.4|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: unspecified [text/html]
Saving to: 'config.mainnet.json'

config.mainnet.json                   [ <=>                                                        ] 119.58K  --.-KB/s    in 0.02s   

2021-04-11 17:42:54 (5.36 MB/s) - 'config.mainnet.json' saved [122453]

root@NLDW1-4-17-14:~/linux-amd64# ls
config.mainnet.json  default.json  nknc  nknd  web
root@NLDW1-4-17-14:~/linux-amd64#    

?

**Comment by rajakhan12** [comment]
nohub ./nknd -p (mypasswrd) &
 i use that commad  but its give me error 

[1] 5489
root@NLDW1-4-17-14:~/linux-amd64# 
Command 'nohub' not found, did you mean:

  command 'nohup' from deb coreutils (8.30-3ubuntu2)

Try: apt install <deb name>

**Comment by rajakhan12** [comment]
I m running on my own server not on coreutils , how i can run note ? which command

**Comment by rajakhan12** [comment]
Post http://localhost:30003: dial tcp [::1]:30003: connect: connection refused

now getting this error any help

**Comment by bufrr** [comment]
> Post http://localhost:30003: dial tcp [::1]:30003: connect: connection refused
> 
> now getting this error any help

You can check if nknd is running by `ps aux | grep nknd` , if nknd is not running, please using `./nknd` then check if nknd print any error.

**Comment by yilunzhang** [comment]
> nohub ./nknd -p (mypasswrd) &
> i use that commad but its give me error

You probably copied the wrong command, it should be `nohup` instead of `nohub`
BTW it's not recommended to use nohup because it will not restart nknd if it exits.
I would suggest you to check out this wiki if you have time: https://forum.nkn.org/t/nkn-mining-guide-for-mainnet-wiki-version/1720
