### ISSUE TITLE
Fast sync for node without local ChainDB

### ISSUE THREAD

**Issue by yilunzhang** [nknorg/nkn#773]
### Issue-Type (put a `x` sign in the square brackets)
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement

The current way of syncing blocks is to compute latest state root from local ledger, get all missing blocks from neighbor sequentially, apply each txn in block to compute the state root after each block, do it for all blocks until the latest height. State pruning is performed during syncing to save disk space.

This approach is efficient if a node is near the latest height and only missing a small portion of whole block history. However, when a node first join the network, he has no local ledger, and the current approach is quite slow.

A more efficient way to sync whole blockchain data is to get the whole state trie at block height (latest - X) from neighbors directly, then get all blocks since that height and apply them sequentially to get all states since block height (latest - X) while doing state pruning just as before.

For backward compatibility and data integrity, I also suggest getting all blocks before height (latest - X). Since we don't need to compute or prune states between height 0-(latest - X), it will still be a lot faster than before.

**Comment by susLimbaugh** [comment]
Would you mind expanding upon what you mean here? It seems to me that you are the dev, is this feature to be implemented in the near future? Is this something we would need to configure ourselves?

**Comment by yilunzhang** [comment]
> Would you mind expanding upon what you mean here?

Basically you can think of it as a much faster way to sync blocks from scratch, and we expect it to replace the current ChainDB snapshot that many people are using.

> is this feature to be implemented in the near future? Is this something we would need to configure ourselves?

We are planning to implement this soon. It should either be used by default, or can be enabled by a simple start argument.

**Comment by steven87vt** [comment]
Is it not possible to have nodes post the ledger files to a s3 bucket or something in segments  for new clients to simply download and chain together like an index.html page and chunked javascript packages?

**Comment by yilunzhang** [comment]
The owner of that bucket is going to pay huge amount of traffic cost if it's public, as we have paid before 😂 You can think of the fast sync as a decentralized and secure ledger, i.e. a better replacement

**Comment by yilunzhang** [comment]
Implemented in #824
