### ISSUE TITLE
Please rebuild / update the Latest tag image on hub.docker.com

### ISSUE THREAD

**Issue by solipsist01** [nknorg/nkn#776]
Hello.

Can you please rebuild / update the 'latest' image on hub.docker.com to 2.1.1
this image also has the ARM versions. the current 2.1.1 only has AMD64
the latest ARM image hosted on hub.docker.com is incompatible with the current mainnet.

**Comment by grolnn** [comment]
I second this. The latest image doesn't run. I'm able to manually pull v2.1.1 on my NUC, but not on my Pi. Probably the wrong architecture? Not sure though.

**Comment by solipsist01** [comment]
i was able to manually build it like so:

git clone https://github.com/nknorg/nkn.git /docker/builders/nkn
cd /docker/builders/nkn
docker build -f docker/Dockerfile -t nknorg/nkn .

**Comment by grolnn** [comment]
> i was able to manually build it like so:
> 
> git clone https://github.com/nknorg/nkn.git /docker/builders/nkn
> cd /docker/builders/nkn
> docker build -f docker/Dockerfile -t nknorg/nkn .

Ah thanks for this. Building went well, but how do I use this build in a docker run command? If I use "image: nknorg/nkn" in docker-compose.yml it keeps pulling the online version.

**Comment by yilunzhang** [comment]
Very strange. We have been using the same command to build and push amd64/arm32/arm64 to docker hub: https://github.com/nknorg/nkn/blob/master/Makefile#L102
If it's not working, that means something was changed either on docker side or dockerhub side....
Can you try again now? I manually trigger the build process, and at least it shows up on docker hub
![unknown-7](https://user-images.githubusercontent.com/2791582/116156500-6dad8a80-a6a0-11eb-8c5f-0194d0a0597d.png)

**Comment by solipsist01** [comment]
works perfectly :)

**Comment by grolnn** [comment]
> Very strange. We have been using the same command to build and push amd64/arm32/arm64 to docker hub: https://github.com/nknorg/nkn/blob/master/Makefile#L102
> If it's not working, that means something was changed either on docker side or dockerhub side....
> Can you try again now? I manually trigger the build process, and at least it shows up on docker hub
> ![unknown-7](https://user-images.githubusercontent.com/2791582/116156500-6dad8a80-a6a0-11eb-8c5f-0194d0a0597d.png)

Yes odd, seems to be working again! Case closed! ;)
