### ISSUE TITLE
NKN Node Causing Connectivity Drops?

### ISSUE THREAD

**Issue by susLimbaugh** [nknorg/nkn#778]
### Description of the issue
Describe the issue you are experiencing.

### Issue-Type (put a `x` sign in the square brackets)
- [x ] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [x ] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* OS
* Linux RPI OS
* Go version
* 1.15.1
* Release tag/commit of the code
* not sure

### Expected behaviour
What should happen?
Node should not create issues for my internet and other node operators internet's

### Actual behaviour
What is actually happening?
Node seems to be causing connectivity drops. My wifi dropped, as soon as it came back up I checked nstatus.org and less than 5% of the nodes that were online before were now online (~100,000 down to 6,500).  This leads  me to believe my connectivity is due to NKN and not other sources. Is there a way to avoid these drops or at the very least mitigate?

### Steps to reproduce
1. Provide detailed steps
2. how to reproduce this issue

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

**Comment by yilunzhang** [comment]
When did that happen? There was a few hours (01:30 April 26 UTC - 05:30 April 26 UTC) when there was an abnormal more amount of traffic in network, and we fixed it in the latest version (v2.1.2).

> My wifi dropped, as soon as it came back up I checked nstatus.org and less than 5% of the nodes that were online before were now online (~100,000 down to 6,500)

BTW don't always trust the node count. The data comes from a single crawler, which is centralized and fragile. Every now and then it shows 0 nodes in network 😂

**Comment by susLimbaugh** [comment]
@yilunzhang turns out it was just my node needing a protocol version update. I've been seeing more drops lately, but I am trying to host other sorts of nodes as well, so seems one of the other nodes is the source of the issue. Thanks!
