### ISSUE TITLE
consensus bug?

### ISSUE THREAD

**Issue by jianghan1976** [nknorg/nkn#794]
### Description of the issue
in /consensus/proposing.go Line 42
if !consensus.isBlockProposer(**currentHeight**, timestamp) {					log.Errorf("I'm no longer the block proposer at height %d at %v", expectedHeight, timestamp)					break				}
**currentHeight** ? any bugs ?

### Issue-Type (put a `x` sign in the square brackets)
- [ x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [ x] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* OS
* Go version
* Release tag/commit of the code

### Expected behaviour
consensus fault

### Actual behaviour
None

### Steps to reproduce
1. Provide detailed steps
2. how to reproduce this issue

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

**Comment by bufrr** [comment]
Please check https://github.com/nknorg/nkn/blob/e32a140d1b7a0b26078bed80fdf3c533874f8fc0/consensus/proposing.go#L73
