### ISSUE TITLE
GetNextBlockSigner Problem

### ISSUE THREAD

**Issue by jianghan1976** [nknorg/nkn#795]
### Description of the issue
In BlockValidator.go Line302
	case pb.WinnerType_BLOCK_SIGNER:
There is no subsequent processing， will return string with zero length, Difficulties in triggering consensus

### Issue-Type (put a `x` sign in the square brackets)
- [ x] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [ x] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* OS
* Go version
* Release tag/commit of the code

### Expected behaviour
What should happen?

### Actual behaviour
What is actually happening?

### Steps to reproduce
1. Provide detailed steps
2. how to reproduce this issue

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

**Comment by yilunzhang** [comment]
This is the right behavior. There is no defined block proposer if `winnerType == pb.WinnerType_BLOCK_SIGNER` and `timeSinceLastBlock < proposerChangeTime`. One needs to wait until `timeSinceLastBlock >= proposerChangeTime` to have a block proposer.
