### ISSUE TITLE
Add SyncMode to JSON RPC and nknc

### ISSUE THREAD

**Issue by zbruceli** [nknorg/nkn#825]
### Description of the issue
Today the node JSON RPC does not return the value of SyncMode. It will be good to add this.

### Issue-Type (put a `x` sign in the square brackets)
- [ ] bug report
- [ x] feature request
- [ ] Documentation improvement

### Checklist
- [ x] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* OS: Ubuntu Linux 18.04 LTS
* Go version: 
* Release tag/commit of the code: 2.1.7

**Comment by abebeos** [comment]
@yilunzhang , seems closable.
