### ISSUE TITLE
not really an issue : use a domain_name instead of IP

### ISSUE THREAD

**Issue by nitad54448** [nknorg/nkn#826]
### Description of the issue
I dont have a fixed IP but I have a DNS (with the A record updated every hour). Can I use a DNS instead of the IP ? It is not clear in the configuration

### Issue-Type (put a `x` sign in the square brackets)
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement

### Checklist
- [x ] Running latest version of code.
- [x ] This issue has not been reported earlier.

### Your environment
* OS
Ubuntu 20.04 LTS

**Comment by yilunzhang** [comment]
The hostname field in config is a bit relevant, but it's not going to work well if your IP address change regularly. Typically when IP is changed, existing connections will be cut off, which basically makes nknd not working properly...
