### ISSUE TITLE
Use UDP instead of TCP for consensus?

### ISSUE THREAD

**Issue by yilunzhang** [nknorg/nkn#83]
Block and consensus related data transmission could use significant bandwidth. Switching from TCP to UDP could enhance performance, and will not affect correctness due to the fault tolerance of consensus algorithm. Any thoughts are appreciated.

**Comment by rreive** [comment]
This makes sense, given the UDP payload is lightweight (<48 bytes) to support the consensus process and you set the  underlying L3 IP DTU to 48 bytes, so it get's processed quickly throught the queues of intermediate routers found in the selected best P2P path. Traversing Firewalls is much easier with UDP, as  Firewalls in the path to get to router nodes existing in a DMZ (Enterprise use case) are likely by default to block the port ID (explicitly opening up a port to allow the P2P path, is a manual admin burden you don't want)

**Comment by yilunzhang** [comment]
Agreed. We will probably handle this later as current (bandwidth) bottleneck is on the cryptography side.

**Comment by rreive** [comment]
Have you considered uTP "Hole punching" over UDP to avoid being blocked explicitly by ISPs or Cloud providers employing Firewall's Scanning UDP selectively with RT ACLs ?

**Comment by rreive** [comment]
Here is the link

https://github.com/basarevych/utp-punch

**Comment by yilunzhang** [comment]
Implemented in #347
