### ISSUE TITLE
about upnp register.

### ISSUE THREAD

**Issue by allegrox** [nknorg/nkn#830]
### Description of the issue
When my node is deployed under the three-layer switching network architecture, the node cannot register UPnP on the router. If the node and the router are in the same two-layer network, it can register UPnP service.

### Issue-Type (put a `x` sign in the square brackets)
- [ x] bug report
- [ x] feature request
- [ ] Documentation improvement

### Checklist
- [ x] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* OS
CentOS 7.9
* Go version
2.1.7
* Release tag/commit of the code

### Expected behaviour
What should happen?

### Actual behaviour
What is actually happening?

### Steps to reproduce
1. Provide detailed steps
2. how to reproduce this issue

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

**Comment by yilunzhang** [comment]
nknd is using https://gitlab.com/NebulousLabs/go-upnp and https://github.com/fd/go-nat to set up upnp automatically. If both of the libraries fail to set it up automatically, you need to set it manually. You probably need to manually set up upnp if it's more than two layer.

**Comment by allegrox** [comment]
May I specify the ip address of the router for the nknd to register the UPnP port?

**Comment by yilunzhang** [comment]
I don't think those two libraries support that. Their exposed API are pretty simple...
