### ISSUE TITLE
Implement transaction pool sync

### ISSUE THREAD

**Issue by yilunzhang** [nknorg/nkn#832]
### Issue-Type (put a `x` sign in the square brackets)
- [ ] bug report
- [x] feature request
- [ ] Documentation improvement

### Description of the issue

Currently the only way for transaction to propagate is the tree broadcasting algorithm in nnet. This is not enough to guarantee every node in the network will receive a txn eventually. A few examples:

- Node without inbound neighbors (e.g. no public ip address, or has firewall) will not receive anything from tree broadcasting.
- Node cannot receive txn broadcasted when it was offline, and thus cannot receive txn of the same account because of non-continuous nonce.

Ideally we would like every node in the network to be able to receive all txn in txn pool, regardless of its network condition and when it gets online. This can be achieved by implementing a transaction pool sync mechanism. An example version: each node periodically ask a neighbor (maybe random, or sequential query), what is the latest nonce of all (or one) account in txn pool, and compare response with local txn pool. If neighbor has higher nonce than local txn pool, get those additional txn.

There are a few caveats though. For example, when txn replacement occurs, how should we prevent old txn from replacing new txn with this txn pool mechanism. The protocol should be well designed to prevent such issues.

**Comment by abebeos** [comment]
@yilunzhang , closable?
