### ISSUE TITLE
Possible error in wiki about network topology

### ISSUE THREAD

**Issue by grondilu** [nknorg/nkn#848]
In the tech design doc wiki page, network topology section, it is written that neighbors of x includes the set {y|x is a _successor_ of y}.

Shouldn't that be {y|x is a **neighbor** of y}  ?

**Comment by yilunzhang** [comment]
It's the same because the only other neighbors specified in the doc are successors of some offset (including successors and finger tables). But in general you are right if there are more neighbors than successors, which we do have now.

**Comment by grondilu** [comment]
> the only other neighbors specified in the doc are successors of some offset

But those are successors of these offset addresses (

**Comment by yilunzhang** [comment]
Yeah you are absolutely right. We typically call those successors of offset addresses finger table. I have changed the wiki page as you suggested. Feel free to re-open the issue if you find any other problems! Thanks!

**Comment by grondilu** [comment]
> Yeah you are absolutely right. We typically call those successors of offset addresses finger table. I have changed the wiki page as you suggested. Feel free to re-open the issue if you find any other problems! Thanks!

I cannot reopen the issue but I may open an other one
