### ISSUE TITLE
Wiki : possible error for the first byte of SignatureScript

### ISSUE THREAD

**Issue by grondilu** [nknorg/nkn#849]
On the wiki page about Wallet specification, it is written :

    SignatureScript <- {0x21||encoding_point(publickey)||0xAC}

but then if I use this 33 (0x21) length to reproduce the example given on the subpage about the wallet address :

    go run util/pubkey2addr/pubkey2addr.go 1111111122222222333333334444444455555555666666667777777788888888
    NKNRyqyBLzghJWGwogJTKNFM5WUnoqopiTYV

It only works if I use 0x20 instead.  I suppose this makes sense, as the push OP for the length of the public key (?).  Unless the length is for the whole script?

I haven't looked into bitcoin scripting for a while so I may be missing something, but I do think it's 0x20 here, not 0x21.  And in fact the go code does push the length of the pubkey :
https://github.com/nknorg/nkn/blob/fd9c5ed08623bc58b43c9f8db6de3beb51f0db4c/program/program.go#L127

**Comment by yilunzhang** [comment]
Thanks for pointing this out. The first byte is the length of the public key, which was 33 when we were using ECDSA in testnet phase (before migrated to Ed25519). The wiki really needs to be updated...

We have changed quite a few things to the wallet scheme. An up to date scheme can be found at https://docs.nkn.org/docs/wallet-json-format. I will add this link to the wiki page as well
