### ISSUE TITLE
RPC calls do not accept `null` as parameters

### ISSUE THREAD

**Issue by grondilu** [nknorg/nkn#850]
$ server=http://mainnet-seed-0004.nkn.org:30003
    $ curl --request POST --cookie cookies.txt --data '{"method":"getversion","params": null}' "$server"
    {"error":{"code":-42002,"message":"INVALID PARAMS"},"id":"1","jsonrpc":"2.0"}

    $ curl --request POST --cookie cookies.txt --data '{"method":"getversion","params": {}}' "$server"
    {"id":"1","jsonrpc":"2.0","result":"v2.1.7-1-g677e-dirty"}

Not sure if this is conform to the JSON-RPC spec or not, but I think this prevents me from connecting using an RPC library in my language.

**Comment by yilunzhang** [comment]
Fixed in #851
