### ISSUE TITLE
[ERROR] GID 1, seed list in config file should not be blank

### ISSUE THREAD

**Issue by fhl1349** [nknorg/nkn#853]
### Description of the issue
after ./nknd   it says “[ERROR] GID 1, seed list in config file should not be blank”，what's wrong?

### Issue-Type (put a `x` sign in the square brackets)
- [X ] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [ ] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* center os 7.6
* Go version: go1.18.1 linux/amd64
* Release tag/commit of the code:last

### Expected behaviour
What should happen?

### Actual behaviour
What is actually happening?

### Steps to reproduce
1. Provide detailed steps
2. how to reproduce this issue

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

**Comment by yilunzhang** [comment]
nknd expects a `config.json` in the current working directory, check [this section in readme](https://github.com/nknorg/nkn#configuration)
