### ISSUE TITLE
[ERROR] GID 1, POST request: Post "http://localhost:30003": dial tcp [::1]:30003: connect: connection refused

### ISSUE THREAD

**Issue by helo112233** [nknorg/nkn#854]
### Description of the issue
I have opened all ports of my firewall, but when I enter the command to check wallet balance: ". /nknc wallet -l balance "
still says: "[ERROR] GID 1, POST request: Post "http://localhost:30003": dial tcp [::1]:30003: connect: connection refused
Post "http://localhost:30003": dial tcp [::1]:30003: connect: connection refused"
What's going on? I am a new miner, help me thanks!

### Issue-Type (put a `x` sign in the square brackets)
- [X ] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [ ] Running latest version of code.
- [ ] This issue has not been reported earlier.

### Your environment
* OS:cent os 7.6
* Go version  go1.18.1 linux/amd64
* Release tag/commit of the code:last

### Expected behaviour
What should happen?

### Actual behaviour
What is actually happening?

### Steps to reproduce
1. Provide detailed steps
2. how to reproduce this issue

### Any extra info ( for eg. code snippet to reproduce, logs, etc. )
If necessary, provide some extra information like code-snippets or error-logs.

**Comment by yilunzhang** [comment]
You don't have to open any port in firewall.

By default `nknc` will try to connect to your local nknd at `127.0.0.1:30003`. If you don't have a local node running, or if you want to connect to remove node, you can add `--ip x.x.x.x` argument to nknc, for example `nknc --ip x.x.x.x wallet -l balance`.

**Comment by helo112233** [comment]
How can I fix the error I mentioned above? Now I can't check my wallet balance.

**Comment by yilunzhang** [comment]
As I said above, use `--ip` argument to point to a working node's IP address or domain. It doesn't have to be your node, can also be any public node. If you are a miner, you can use your own node for that

**Comment by helo112233** [comment]
Still giving errors, I just check the nodes on my server, is it because my node is not started yet? Because I don't have fee
![image](https://user-images.githubusercontent.com/99348157/164258102-4c023526-394a-4f09-bfea-52cf2cafd6ea.png)

**Comment by yilunzhang** [comment]
You should use `--ip 127.0.0.1`, not `--ip 127.0.0.1:30003`
