### ISSUE TITLE
Why can't I transfer money? Both web-based wallet and app

### ISSUE THREAD

**Issue by helo112233** [nknorg/nkn#855]
Why can't I transfer money? Both web-based wallet and app
![image](https://user-images.githubusercontent.com/99348157/164260899-6495134f-aa20-4fad-a1bd-91a7932b9c2f.png)

**Comment by yilunzhang** [comment]
It says on the page: not sufficient funds....
Note that all pending txn txpool will also be included in computing balance. If you want to replace it, try check the `replace pending transaction` option.

**Comment by MAKA02** [comment]
carding and loading is an act to be done by legitimate people 
need verification on how to get quick cc , PayPal transfers and more ?
have you been looking for a place to buy cc and get legit money TRANSFER services like PayPal,  western union and more ?
visit https://t.me/credit_card_uk

**Comment by MAKA02** [comment]
carding and loading is an act to be done by legitimate people 
need verification on how to get quick cc , PayPal transfers and more ?
have you been looking for a place to buy cc and get legit money TRANSFER services like PayPal,  western union and more ?
visit https://t.me/credit_card_uk

**Comment by Adminsupportt** [comment]
Kindly follow the step on this link to talk to the customer care service directly on your issues anyone asking you to DM is a scam
https://direct.lc.chat/14201763/
