### ISSUE TITLE
Proposals nkn Products

### ISSUE THREAD

**Issue by Pantyhose-X** [nknorg/nkn#863]
Please build a search engine that you can base on https://github.com/searxng/searxng

### Why you need
We do not like google, bing, yahoo to obtain user privacy, these search engines.
We believe in the blockchain network, the protection of privacy.
You can claim to be the world's first, blockchain search engine

Proposals nkn Multi-Hop vpn

### Why you need
You can claim to be the world's first, blockchain vpn

**Comment by gabriellemon** [comment]
I don't think they claim to be the worlds first blockchain search engine, nor first blockchain vpn. This looks cool though, but if you wanted it I think it would be better for the community to build it. I'd also recommend checking out Presearch. They do what searxng does but it is hosted which allows for normal users to utilize non logged search.

**Comment by yilunzhang** [comment]
Closing this issue as it's not related to this repo. We can discuss more on forum/discord/etc
