### ISSUE TITLE
Setting up private local testnet?

### ISSUE THREAD

**Issue by lonnietc** [nknorg/nkn#881]
### Description of the issue
Describe the issue you are experiencing.

Looking for the steps to set up a private local testnet across a few Windows and Linux machines that I have here to experiment more.

### Issue-Type (put a `x` sign in the square brackets)
- Documentation improvement

### Checklist
- Running latest version of code. --- Latest Github clone
- This issue has not been reported earlier -- Could not find any information within the "Dev" or "Testnet" channels on Discord nor in the Wiki or other NKN documentation so far.

### Your environment
* OS  -- Primary Windows 10/11 x64 and Ubuntu 21.04 Linux
* Go version -- v1.19.3

I would like to get some information to set up a private local testnet from scratch on Windows/Linux and then be able to test some simple client applications.

Any help that you could provide would be greatly appreciated.
Thanks in advance.

**Comment by lonnietc** [comment]
Update:

In the NKN Configuration section, I found:

```
We provide a few sample config.json:

config.mainnet.json: join the mainnet
config.testnet.json: join the testnet
config.local.json: create and join a private chain on your localhost
```

From this I could copy the "config.local.json" which is supposed to create a private chain on the localhost, but then the question is on how to generate the Genesis Block and set up the other nodes on other local machines like in the TESTNET config:

```
{
  "HttpWsPort": 30002,
  "HttpJsonPort": 30003,
  "SeedList": [
    "http://devnet-seed-0001.nkn.org:30003",
    "http://devnet-seed-0002.nkn.org:30003",
    "http://devnet-seed-0003.nkn.org:30003",
    "http://devnet-seed-0004.nkn.org:30003"
  ],
  "GenesisBlockProposer": "0149c42944eea91f094c16538eff0449d4d1e236f31c8c706b2e40e98402984c",
  "BeneficiaryAddr": ""
}
```

**Comment by lonnietc** [comment]
We can close this as I think that I am making progress by using:

```
https://github.com/nknorg/nkn/wiki/Create-a-Private-Chain
```

It seems that the GenesisBlockProposer is the Key that was made when I created the initial wallet.

I need to locate all of the possible configuration options for the wallet and server node.

**Comment by yilunzhang** [comment]
`GenesisBlockProposer` can be the public key of any node's wallet as long as that node is in the network during bootstrap phase

**Comment by yilunzhang** [comment]
> Then, I have a config.json for each node and am wondering if I need to have different ports for each testX node in their particular config.json as well?

If you use `config.local.json` as template, each node will automatically increment its port when it finds out the default one is in use. Just give a few seconds between node launch.

> Is there a utility or way of calling the nknd.exe to see if they are, in fact, connected?

Try `./nknc --port xxxxx info --neighbor` where `xxxxx` is the RPC port of the node you are trying to connect to.

**Comment by lonnietc** [comment]
Thanks for the information and I will give it a try on the local private testnet that I am setting up.

On a side note, I am also setting up a mainnet node to run as well and am work getting the needed NKN in my wallet address so that I can create the ID for the node which seems to require 10 NKN.

With that in mind, what are the TPS speeds of the NKN network for confirmations on transactions?

**Comment by yilunzhang** [comment]
> On a side note, I am also setting up a mainnet node to run as well and am work getting the needed NKN in my wallet address so that I can create the ID for the node which seems to require 10 NKN.

Feel free to ping me on discord if you need 10 mainnet NKN for testing.

> With that in mind, what are the TPS speeds of the NKN network for confirmations on transactions?

TPS is mostly restricted by the average hardware spec of nodes in network (CPU, bandwidth, etc), not our algorithm as we have make almost every part scalable (e.g. consensus, network layer). So basically a NKN network consists of data center servers will have a lot higher TPS capability than a NKN network of raspberry pi, even if they are running the same code. Currently the network don't have many transactions because the key functionality of NKN network (i.e. data transmission) is purely offchain.
