### ISSUE TITLE
Addition of a Proof-of-Participation (PoP) Consensus?

### ISSUE THREAD

**Issue by lonnietc** [nknorg/nkn#882]
### Description of the issue
Adding an additional consensus for Proof-of-Participation (PoP)

### Issue-Type (put a `x` sign in the square brackets)
- [X] feature request

### Checklist
- [X] Running latest version of code.

### Your environment
* OS   --- Windows 10/11 (x64) and Ubuntu 21.04 (x64)
* Go version --- v1.19.3

As I understand the NKN consensus approach it uses a "Proof-of-Relay (PoR)" which allows nodes to get rewarded based upon the relay and transmittal of network packets through the NKN Network Mesh and is a really fine approach.

I also am thinking about all of the user nodes that are online now (30K - 50K if I remember correctly) and with the question about packet and information traversal though the mesh. It seems to me that if a person has a running node, then it is completely by chance that a network packet would happen to get routed through their node and that they have no control over if that happens or not.

While true that they get rewarded "mining" if packets come through their node, they do not get any type of rewards for their node being available, online, and ready to participate. 

Given that those "waiting" nodes are still consuming resources like bandwidth, power, storage space, etc. and not getting any type of rewards, I think that this is a small shortcoming to the NKN system that could easily be corrected by adding an additional Consensus Mechanism for perhaps something like "Proof-of-Participation (PoP)" which could be an added module to augment the PoR Consensus.

The Proof-of-Participation (PoP) would effectively mine small rewards for having a node online and running while the PoR Consensus would manage the reward mining for the relay of packets through the mesh network.

It seems to me that to have PoR and PoP would cover all of the base cases and also enhance favorable desirability for users to set up more nodes and thus expand the NKN network.

On this idea, is NKN modular enough to add an additional consensus for something like PoP? This might be interesting to investigate in a fork on a local private testnet as well.

Any thoughts on this?

Thanks, and have a great day

**Comment by yilunzhang** [comment]
We have considered something similar before but didn't end up well. The idea of PoP is very hard to prove cryptographically. In order to prove a node is online, you would need to trust the proof from its neighbors, but what if its neighbors are fake (i.e. just a key pair but not actually online)? In the extreme case, an attacker could create a huge number of valid ID and provide proof to each other. They can also perform DDoS attack on honest nodes by not providing valid proof. If you have a more complicated mechanism trying to solve this problem and do quantitative analysis, you will find out that the proof size needed to be safe enough is extremely high (like making a block thousands of times larger) and not practical.

**Comment by lonnietc** [comment]
Hello @yilunzhang,

The picture of things is clearer now, and I appreciate you taking the time to discuss them with me.

I was thinking about NKN and the PoR by itself last night which raised a question for me.

As I understand, the PoR is the mining when network packets pass, or are relayed, through NKN nodes. Additionally, there is now an initial ID Creation (10 NKN) and that there are no other network fees or usage fees associated with users sending information from node to node. 

This would imply that relay mining is the main source of distribution and that the exchanges allow for trading for which they may have fees as well.

Is this about correct?

My question, if this is correct, is based on the hypothetical problem in this scenario that a "bad" actor might be able to set up a few local nodes that are effectively in their own neighborhood (i.e. within a ping radius to establish a neighborhood I am guessing if how NKN does it) and then set up some SDK applications within that local group that simply pass data back and forth among that neighborhood group.  

Would this not give them an unfair mining advantage in the PoR scheme of things?

I could be missing something in the NKN with PoR approach and am sorry if that is the case here.

**Comment by yilunzhang** [comment]
> This would imply that relay mining is the main source of distribution and that the exchanges allow for trading for which they may have fees as well.

Yes that's right.

> Would this not give them an unfair mining advantage in the PoR scheme of things?

There are a few mechanisms to prevent this. For example:
- Relay path has to follow Chord DHT routing rule to be valid, so one cannot form path arbitrary
- Signature chain weight grows exponentially with its length, so short path (easier to form) has extremely low chance to be selected
- Path that contains nodes which recently appeared in sigchain will have exponential penalty

These mechanisms make it hard for anyone to gain unfair advantage by forming a private group and send data within them.

**Comment by lonnietc** [comment]
Thanks and those are really good ways to address that concern.

I am thinking now that once the C/C++ SDK is released then I may not need to be concerned about adding an additional PoP consensus now since the PoR may cover things the way that I need.

I just need to work out a good P2P filesystem (either Golang or C++) application and then integrate NKN into the user server node (C/C++) application as these 2 applications will work together an communicate to other nodes via the NKN (nnet) mesh network.  This will be exciting to see come together, and I will experiment a lot on my local private testnet during the development which is already underway, but may end up having a few more questions related to that as well.

Ok, I think that you have done an awesome job in answering my questions and I truly appreciate it.  I am on Discord as "TallyLC" and maybe we can chat more about my specific case and look at what synergy may be present.

We can probably go ahead and close this up.
