### ISSUE TITLE
C/C++ SDK Release?

### ISSUE THREAD

**Issue by lonnietc** [nknorg/nkn#883]
Hello,

I am told that there is a C/C++ SDK in development but has not been released yet and am wondering when this might happen since one of the components in my project is a C++ based application that I wish to integrate NKN into so that it will pass its communications through a local full node.

Any ideas as to when this might get released?

I would be happy to also be a part of the Beta testing for this as well if that is possible.

Thanks, and have a great day.

**Comment by yilunzhang** [comment]
We have a working version and have been using it for a while internally, but the RAM usage hasn't been reduced to an ideal level. We will probably open it to public soon so you can try it out

**Comment by lonnietc** [comment]
That would be AWESOME given that I have project which will be using a Golang application as well as a C++ application and I want to integrate it with the NKN C++ SDK code so that it will use the network mesh.

Looks like I am really making some good progress with my research and investigations on using NKN and with all of your wonderful help. I just wished that I would have found NKN much earlier in my development which would have saved me a LOT of time from looking at other things.

**Comment by lonnietc** [comment]
If you need Beta testers for this, then please let me know as well and I'll be happy to do what I can to help.

**Comment by abebeos** [comment]
> I just wished that I would have found NKN much earlier in my development

@lonnietc , may I ask what your use-case is?

**Comment by abebeos** [comment]
@lonnietc , there is https://github.com/gdmmx/nkn-sdk-cpp

**Comment by abebeos** [comment]
> We have a working version and have been using it for a while internally

Are you referring to this one: https://github.com/gdmmx/nkn-sdk-cpp ?

Possibly just move it over to nknorg and mark it as "not for production use".

**Comment by abebeos** [comment]
> We have a working version and have been using it for a while internally

@yilunzhang Are you referring to this one: https://github.com/gdmmx/nkn-sdk-cpp ?

Possibly just move it over to nknorg and mark it as "not for production use".

**Comment by yilunzhang** [comment]
That's what we are planning to do soon after some clean up and change.

**Comment by abebeos** [comment]
You should do it yesterday.

**Comment by yilunzhang** [comment]
You should know that some dev are still in national holiday right now, and some won't be back til next week. Not in your country but in theirs. Our dev are distributed globally, you should get used to that.

Plus we have some more changes we plan to do before doing it.

**Comment by abebeos** [comment]
It looks strange that you don't keep it under "nknorg". The sum of those smaller "stranger things" add up to "super-strange, what are they doing there?"

I'll use another term: It looks purely unprofessional.

> Plus we have some more changes we plan to do before doing it.

No, you don't. There is zero logic in this.

**Comment by yilunzhang** [comment]
We have it under nknorg, just not public yet. The repo you pointed to is not to be official nkn sdk (yet). We never sent the link to any other people saying "hey this is our c++ sdk", you did.

**Comment by abebeos** [comment]
> We never sent the link to any other people saying "hey this is our c++ sdk", you did.

I did, but you never replied with "this is not the actual version". Anyone searching for "nkn-cpp-sdk" will locate this repo.

You are open-source, you must(!) open your development more and become "open project", otherwise users complain rightfully.

(anyways, me at this point even more frustrated, but backing off for now)

**Comment by abebeos** [comment]
@yilunzhang , just realized that we're on the public repo.

*@&#)$&@)#(*%&)(

**Comment by yilunzhang** [comment]
Lol all good, at least no private key leaked XD

**Comment by abebeos** [comment]
(ok, my comments are fine, I just deleted one of my comments that had a more "in-private" tenor)

**Comment by abebeos** [comment]
Ok, even if gdmmx is drinking margaritas on sunny beaches, a visitor can easily land on this PR to understand the status:

https://github.com/gdmmx/nkn-sdk-cpp/pull/1

**Comment by newt7744** [comment]
Is there an expected release date?

**Comment by yilunzhang** [comment]
This week!

**Comment by yilunzhang** [comment]
Finally here: https://github.com/nknorg/nkn-sdk-cpp

**Comment by yilunzhang** [comment]
We are still working on the documentation though. In the meantime feel free to ask questions in Github or discord
