### ISSUE TITLE
Does NKN put out a heartbeat pulse?

### ISSUE THREAD

**Issue by lonnietc** [nknorg/nkn#884]
Hello,

This is not really a problem but more of a question.

I am wondering if NKN or the underlying nnet puts out any type of heartbeat packet pulse that might occur periodically, say 10 packets per minutes or something like that that perhaps to ensure that all of the nodes are active in the mesh network?

Just wondering about how the network manages to ensure that all of the connected nodes are active and listening.

Thanks

**Comment by yilunzhang** [comment]
Yes it does https://github.com/nknorg/nnet/blob/92177722ff0e46152a6408b24a008b853eeae1f6/node/remotenode.go#L514

**Comment by lonnietc** [comment]
Thanks and I will definitely look into that more since I was thinking about how that might be used is there were to be some type of Proof-of-Participation (PoP) consensus addition to be used in conjunction with the Proof-of-Relay (PoR) for nodes that are attached and operational within the mesh network but are basically just waiting for network traffic.   

This goes with my other PoP issue idea 

https://github.com/nknorg/nkn/issues/882

**Comment by yilunzhang** [comment]
We can discuss PoP related topic in the other issue you created.

> Another small incentive, at least in my mind, would be to remove to 10 NKN fee to create an ID and setup an active node.

Actually the fee was introduced recently as a way to mitigate sybil attack. Being able to get large number of ID for free could be dangerous.

> Lastly, can you please tell me what the purpose is of the
> DonationAddress = "NKNaaaaaaaaaaaaaaaaaaaaaaaaaaaeJ6gxa"

Basically this is the address to receive ID fee and other donation. Tokens in this address will be distributed to miners gradually by increasing future mining rewards. This is a mechanism to encourage long term miners.

**Comment by lonnietc** [comment]
Thanks and I can understand now about the fee that NKN has introduced. I have some coins in Doge that I was experimenting with (I'm not a serious trader or anything like that but really like the blockchain technology and efforts like NKN) so I was trying to convert some of that to NKN on Coinbase or some other exchange as I am also just on a simple exchange like that for now and will have to see about converting some today.

Regarding the sybil attack process, I can also understand the need, especially for the Mainnet, although for may experimental private testnet, the use case is just a bit different and a sybil attack is "almost" unpractical for the user.  I can reach out to you on the Discord channel and we can discuss it more in detail, privately which is better since it could also be a very good alignment with NKN, ok.
