### ISSUE TITLE
Crashes out on long runs for Windows and Linux.

### ISSUE THREAD

**Issue by lonnietc** [nknorg/nkn#886]
### Description of the issue
As an initial test for the nknd daemon, I started a copy with the everything configured correctly on a VPS server with public IP and no firewall and which is online and running 24/7 with no limits on up/down loads and running an x86_64 Ubuntu 21.10 OS. 

I just wanted to see how stable it was on a solid server before running it more on local Windows machine as it too crashed out with similar problems recently at which time I decided to test on a VPS that I have on the Internet.

### Issue-Type (put a `x` sign in the square brackets)
- [X] bug report
- [ ] feature request
- [ ] Documentation improvement

### Checklist
- [X] Running latest version of code.

### Your environment
* OS   ---- Ubuntu 21.10
* Go version --- Go v1.19.3

### Expected behaviour
I would expect that the ./nknd daemon server keep running on both Windows and Linux platforms.

### Actual behaviour
Crashes out:

```
2023/01/16 13:11:55.379029 [INFO ] GID 25960592, RefCount height: 1493717, length of refCounts: 167
2023/01/16 13:11:55.397905 [INFO ] GID 25960592, Pruning height: 1477333, length of refCounts: 205
2023/01/16 13:11:55.398093 [INFO ] GID 25960592, # current block height: 1493717, block hash: 084344ebebf6d935eaf7c06082562a9b84e969dfea90d19def619187915fc580
2023/01/16 13:11:55.413070 [INFO ] GID 25960581, RefCount height: 1493718, length of refCounts: 166
2023/01/16 13:11:55.431638 [INFO ] GID 25960581, Pruning height: 1477334, length of refCounts: 264
2023/01/16 13:11:55.431777 [INFO ] GID 25960581, # current block height: 1493718, block hash: f896354093189e4bf6f046346e82204fa66ac75386a957350ff0051c1cc865d8
2023/01/16 13:12:00.781485 [WARN ] GID 147, Handle proposal error: wait for neighbor vote timeout
2023/01/16 13:12:01.378836 [ERROR] GID 354, Find successor for finger table error: Wait for reply timeout
2023/01/16 13:12:02.220657 [ERROR] GID 353, Update finger table error: Wait for reply timeout
2023/01/16 13:12:02.468368 [ERROR] GID 350, Update successors error: Wait for reply timeout
2023/01/16 13:12:03.608373 [INFO ] GID 107, DropTxns: 408 txns (111609 bytes) in txpool, no need to drop
2023/01/16 13:12:04.746435 [ERROR] GID 351, Update predecessor error: Wait for reply timeout
2023/01/16 13:12:08.758916 [INFO ] GID 130, Handle transactions msg error: not sufficient funds
2023/01/16 13:12:09.015663 [ERROR] GID 352, Find predecessors error: Wait for reply timeout
2023/01/16 13:12:09.695902 [ERROR] GID 353, Update finger table error: Wait for reply timeout
2023/01/16 13:12:09.708344 [ERROR] GID 350, Update successors error: Wait for reply timeout
2023/01/16 13:12:11.315184 [ERROR] GID 354, Find successor for finger table error: Wait for reply timeout
2023/01/16 13:12:11.873248 [WARN ] GID 147, Handle proposal error: wait for neighbor vote timeout
2023/01/16 13:12:15.287176 [WARN ] GID 25960586, Get blocks error: Wait for reply timeout
2023/01/16 13:12:15.287340 [WARN ] GID 25960582, Get blocks error: Wait for reply timeout
2023/01/16 13:12:15.398334 [WARN ] GID 25960592, Get blocks error: Wait for reply timeout
2023/01/16 13:12:15.432988 [WARN ] GID 25960581, Get blocks error: Wait for reply timeout
2023/01/16 13:12:15.433196 [ERROR] GID 9526, Sync blocks error with batch size 1: all workers failed
2023/01/16 13:12:15.433299 [FATAL] GID 9526, [consensus.go:L341 func2()] Error syncing blocks: sync blocks error: all workers failed

```

### Steps to reproduce
Run the basic nknd (Linux) or nknd.exe (Windows) for a long duration.

**Comment by yilunzhang** [comment]
Just to clarify, nknd is not designed to keep running under all circumstances. There are cases when nknd decides to exit like the logs you provided. To be more specific, when nknd fails to communicate with (all) its neighbors, it will exit and let node owner to decide what to do. If you want to run it 24/7 in a stable environment where brief network issue will recover automatically (like on a VPS), you should use systemd to restart nknd automatically with your retry policy. This way we are more flexible and won't keep wasting resources when network is really lost.

**Comment by lonnietc** [comment]
I understand now and was not aware that it would exit under various conditions as I do not recall reading that in the documentation so far, but it does make sense from a resource standpoint.

For my interests, I would like to have the nodes always connected into the network mesh and will seek a solution that allows for it to continue or restart although it might be nice to have a programmatic way to have it always active and seek new connections to maintain a local neighborhood.

Thanks again for clearing this up for me as well.
