### ISSUE TITLE
[CRITICAL] missing CI

### ISSUE THREAD

**Issue by abebeos** [nknorg/nkn#890]
I cannot find a public CI that run tests.

Example: #887 was processed without a visible CI run.

## Tasks

* #888
* Add basic CI (example see https://github.com/nknorg/nkn/issues/890#issuecomment-1399258418)

**Comment by yilunzhang** [comment]
We were using travis (https://travis-ci.org/nknorg/nkn) til it was no longer free. Feel free to let us know if you have any recommendations

**Comment by abebeos** [comment]
I believe the github own "Actions" should be the way to go.

I could give it a try, but I still struggle to get the tests running locally (see #888, "make test" fails).

The travis logs for https://travis-ci.org/nknorg/nkn are not available, are you aware what travis executed back then 2 years ago? (documentation states `make`, see https://docs.travis-ci.com/user/languages/go/#default-build-script).

Or asked differently: what do you use locally for testing, and in which environment (alpine, xenial etc.)?

**Comment by abebeos** [comment]
@yilunzhang , for a "quick&dirty" setup, please take a look here:

https://github.com/abebeos/nkn/actions/runs/3975124240/jobs/6814781030

The related workflow file:

https://github.com/abebeos/nkn/actions/runs/3975124240/workflow

Some minor test failures occur.

May I setup this on a separate branch and push a PR for further refinement? Or do you prefer to take this on?
