### ISSUE TITLE
Supports multiple domain names for SSL certificates to apply

### ISSUE THREAD

**Issue by bufrr** [nknorg/nkn#912]
NKND provides WSS and HTTPS protocol services on ports 30004 and 30005, respectively, and therefore requires users to provide or automatically apply for an SSL certificate. Due to some domain name issues during the automatic certificate application process, a domain name list is required to increase the success rate of certificate applications.

To address this issue, we have built-in a list of domains and use them to apply for SSL certificates from Let's Encrypt.

**Comment by abebeos** [comment]
@bufrr , does this issue supersede #747 ? Or is it something different?

**Comment by bufrr** [comment]
> 

Hi, I updated the description of this issue, it is relative to the domain name issue when nodes apply certificates
