### ISSUE TITLE
Missing copyright owner

### ISSUE THREAD

**Issue by abebeos** [nknorg/nkn#913]
Missing copyright owner

https://github.com/nknorg/nkn/blob/aa832aae9a4001c70484c9b3001de89fc3f31eb8/LICENSE#L192

**Comment by yilunzhang** [comment]
Copyright owner is actually here: https://github.com/nknorg/nkn/blob/aa832aae9a4001c70484c9b3001de89fc3f31eb8/LICENSE#L178

The line you linked to is part of the `APPENDIX: How to apply the Apache License to your work.` section. It's part of the boilerplate template.

**Comment by abebeos** [comment]
Oh my...
