### ISSUE TITLE
Process repos

### ISSUE THREAD

**Issue by abebeos** [nknorg/nkn#914]
Forks, Remove or document the reason of existence 

https://github.com/orgs/nknorg/repositories?q=&type=fork&language=&sort=

Archive all unused/deprecated repos

**Comment by yilunzhang** [comment]
Those are in use. The changes compared to original repo can be easily seen by clicking the `This branch is [X commit ahead]` link in the forked repo. They are quite self explained as there are only tiny type changes or dependency changes, and those repos will only be used internally.

**Comment by abebeos** [comment]
@yilunzhang , you closed without processing

*  document the reason of existence
* Archive all unused/deprecated repos

Especially document, thus one can work towards getting the modifications into the original repo.
