### ISSUE TITLE
Add legal location

### ISSUE THREAD

**Issue by abebeos** [nknorg/nkn#917]
NKN
New Kind of Network

40 followers
Mars
https://www.nkn.org/
[contact@nkn.org](mailto:contact@nkn.org)

https://github.com/nknorg

**Comment by yilunzhang** [comment]
NKN as nkn.org does not have a legal location. The team could have multiple legal entities across the world (e.g. NKN labs) but no single one represent the legal location of the nkn.org. This is common for blockchain project, example: https://github.com/ethereum

**Comment by abebeos** [comment]
@yilunzhang , please understand that closing an issue right after commenting can be easily perceived as rude, as it implies "I am right, I do not care to understand your context. The End".

If you want to understand (because I assure you, there are things you simply do not understand/or choose to not understand... ) , please reopen.

(As a sidenote: Ethereum is in no way a reference of "doing things right". They just made tons of money, the technical level and professionalism is low. Not that low that they list "Mars" as their location).
