### ISSUE TITLE
Web UI not accessable running from Docker

### ISSUE THREAD

**Issue by foegra** [nknorg/nkn#979]
WEB UI is not accessible while running on Docker (27.3.1, build ce12230) on Ubuntu 24.04.1

**Comment by yilunzhang** [comment]
Did you follow this part in readme?

> If you would like to enable web GUI interface from outside of the container, you need to replace -p 30001-30005:30001-30005 with -p 30000-30005:30000-30005.

**Comment by foegra** [comment]
Yes, I did follow this from readme.

**Comment by yilunzhang** [comment]
Try adding this to the end? `--web-gui-listen-address 0.0.0.0:30000`

**Comment by foegra** [comment]
No, still nothing. Just in case - other containers work fine with port publishing.

**Comment by yilunzhang** [comment]
Have you tried the command in readme
`docker run -p 30000-30005:30000-30005 -v ${PWD}:/nkn/data --name nkn --rm -it nknorg/nkn`
This one works for me on various OS. I suspect your case might be related to the additional arg `--network macvlan --ip 10.77.88.3` you added
